### ISSUE TITLE
Attractor Obelisk not working consistently in SMP

### ISSUE THREAD

**Issue by Ronzan** [SleepyTrousers/EnderIO#1131]
The attractor obelisk is not pulling in mobs consistently in SMP. I've tested it with zombies and endermen it does work once in a while, like every 5-7th mob will get pulled in the rest won't.
I have tested it in SSP and there it works just fine.
I have also tested the similar device from Thaumic Tinkerer and that works fine in SMP.
Tested with build 237 and 223, running plain forge 1217 server.

**Comment by Dextathelsot** [comment]
I am currently running Direwolf20 1.7.10 v 1.0.3 and got the same Problem. Are there any Workarounds?

**Comment by Kazzamkablam** [comment]
Same issue on Dark Trilogy 1.0.7 when playing on SMP endermen dont get attracted

**Comment by Hund** [comment]
Kinetic attractor from Thaumic Tinkering doesnt work with either. Maybe its something else thats broken that causes it?

**Comment by JelmarG** [comment]
I have the same issue. Endermen don't seem to be attraced to it. In fact, I had about 40 endermen standing in a circle around the attractor, as if they didn't want to approach it. The strange thing is, in previous setups I made, it used to work fine. I did not change versions in the meantime, so that's quite odd.

**Comment by tterrag1098** [comment]
@JelmarG You have an enderman soul vial in the attractor, and the attractor has power?

**Comment by JelmarG** [comment]
Yes, both the enderman soul vial and power are provided. I am using an older version (EnderIO-1.7.10-2.2.5.311), but since it has worked for me before and I saw other people having the same issue, I thought I'd post anyway.

Here are two screenshots of the situation:
![96a0a246bd](https://cloud.githubusercontent.com/assets/4349184/5991997/bc353ce8-aa12-11e4-89bb-109e7fa3b5f3.png)
![fe70bd858e](https://cloud.githubusercontent.com/assets/4349184/5991998/c023c900-aa12-11e4-9524-a9217de7741e.jpg)

The Attractor is in the bottom of the screenshot, 1 block in the floor (same height as the floor, as not to be in front of Killer Joe), which has worked for me in previous mobfarms I've made. The capacitor that's in it isn't necessary, but I had to try everything before posting.

**Comment by knoxz** [comment]
same issue on the latest infinity. mobs just staring.

**Comment by Drullkus** [comment]
Googled and found this issue. Can confirm issue with autospawned NPCs from MFR autospawner in FTB Infinity 1.6.1.

**Comment by tterrag1098** [comment]
Everyone on this issue, see #1668

**Comment by Drullkus** [comment]
Agressive mobs only? Gah.
