### ISSUE TITLE
Farming station crash with Natura berry bushes.

### ISSUE THREAD

**Issue by CodeRage2** [SleepyTrousers/EnderIO#1382]
http://pastebin.com/1V3YWsuc

User placed an Essence berry bush from Natura just before the crash.

**Comment by FiveEYZ** [comment]
i want to give this issue another try, cause we are getting this crash alot 

http://pastebin.com/raw.php?i=N7iZpTX8

Happens when a Tinkers' Contruct: Essence Berry Bush in placed next to the farming station and the crash is when it tries to "harvest" the bush.

tested it on single player and it works fine, no crash
so it only on a dedicated server environment

might also add that i have KCauldron:1.7.10-1448
EnderIO-1.7.10-2.2.8.381
TConstruct-1.7.10-1.8.5

**Comment by tterrag1098** [comment]
@FiveEYZ Can you reproduce this without KCauldron?
