### ISSUE TITLE
Attractor + endermen are still broken theory on why

### ISSUE THREAD

**Issue by kurokuno** [SleepyTrousers/EnderIO#1668]
my theory is that during the day they are not for some reason attracting to it so in mystcraft all day ages it more or less breaks enderman pulling as i find at night in a normal world there likely to go to it

**Comment by 6210classick** [comment]
the best usage for attractors is at mob farms to get them to a specific place like spike hole or a towards killer joe or MFR grinders

you can't just use it to attract hostile mobs during the day especially the nasty Enderman

how it works is it simulate hitting the mob so hostile mobs run towards however since Enderman ignores the player when you attack in the day that result to it not work correctly

**Comment by kurokuno** [comment]
i understand this however i have a cursed earth spawner the world is eternal day and yes the mobs are under ground in the dark but the point is endermen will not react in any world where it is day time "world time" so even tho its a perfectly working mass spawner it refuses to pull endermen for that one simple reason that to me seems like oversight of dark room/powered spawners working in the day time inside a dark room

**Comment by tterrag1098** [comment]
@kurokuno Your theory was partially correct. They stop being attracted because in the day, endermen do not aggro. That's it. I am now forcing the enderman target every tick so they remain attracted. I also needed to stop them teleporting while attracted, because they are hardcoded to do so every time they "lose" their aggro.
