### ISSUE TITLE
[Suggestion] Tool to replace/upgrade a chain of conduits

### ISSUE THREAD

**Issue by DrakeOfTheWest** [SleepyTrousers/EnderIO#1698]
When progressing through the different tiers of power and fluid conduits there always comes the time, when you have to rip out all your old stuff and replace them with higher tier conduits.

I propose a tool, that works similar to the Wand of Equal Trade from Thaumcraft - only for conduits.

It would probably have to have different Modes for Fluids, Energy and possibly AE, just like the YETA wrench. Then on click it would try to traverse the network of the selected conduit type and replace each with a previously selected type in the players inventory remembering the connection settings and ideally giving out a chat massage, if it runs out of conduits before finishing the whole network. That last part is only, so that you don't end up with incompatible conduits next to each other without noticing.

**Comment by 6210classick** [comment]
that's a really cool but remembering the conduit setting ? that's one hard thing to do , however you can just use the Conduit Probe to copy/paste a setting from one conduit to another from the same tier

for now Yeta wrench + Conduit Probe is more than enough because it's so easy to get the highest energy tier once you get access to ender pearls

**Comment by 4rz0** [comment]
I like this idea.
Then again, EnderIO only has 3 conduit tiers, so you'll not replace them that often.

**Comment by matzanivs** [comment]
try held higher conduit in your hand and simply click on lower conduit:)
