### ISSUE TITLE
Servercrash Ender IO Farm

### ISSUE THREAD

**Issue by ghost** [SleepyTrousers/EnderIO#1729]
Hi, my Server is crashing, dont know what happen... Crashlog says Ender IO Farm and Natura Berry...

Crashlog: http://pastebin.com/SRSmLPYT
http://openeye.openmods.info/crashes/22c68dcaed33f871473d6d50a00b3886

Forge: 10.13.2.1286
Ender IO: 2.2.7.325
Natura: 2.2.0.1
Tinkers Construct: 1.8.2a

EDIT:
Ok, i have set "farmEssenceBerriesEnabled=false" and the server is running again...Hope the informations are enough to fix :)

**Comment by predakanga** [comment]
Just encountered this issue myself, doing some debugging.

I'm relatively new to Minecraft modding, but this appears to be a bug either with EnderIO or Forge.

Specifically, the NPE is caused by ItemInWorldManager.thisPlayerMP.playerNetServerHandler == null - can't see anything that would cause that in FakeFarmPlayer, but my obfuscated debugging skills aren't up to snuff.

I can replicate the crash easily under jdb, so please let me know if there's any info I can provide.

**Comment by wlhlm** [comment]
Which version are you using? Their have been a couple of FakePlayer-related fixes in the 422 update. See #3018.

**Comment by predakanga** [comment]
I'm running 421_beta, will grab 422 now and check.

Additionally, the bug seems related to chunk claiming. I'm running FTB Infinity Evolved 2.2.2, which provides chunk claiming through their "FTB Utilities" mod. Unclaiming the chunk containing the berries lets the farm operate correctly.

**Comment by predakanga** [comment]
422 seems to have fixed the bug - I'm no longer able to replicate, even with chunk claiming enabled.

The farm is unable to harvest from claimed chunks, but I believe that's intended behaviour.

Should be safe to mark this resolved - I may be running a different mod setup to the reporter, but my stack trace is identical.

**Comment by HenryLoenwind** [comment]
Oh, another issue for the same problem. Didn't see this one. Tagged properly now.

Problem was that those protection mods change the way vanilla code works in a way that crashes on a fake player that has no network manager. A bit hard to find as all works well with vanilla...
