### ISSUE TITLE
[Suggestion] Conduit Switch change channel color

### ISSUE THREAD

**Issue by LZee** [SleepyTrousers/EnderIO#1741]
The conduit switch can only generate the "red" signal.
Why can not set up the switch channel color?

**Comment by 6210classick** [comment]
does anyone actually uses that ? everybody just uses a lever or buttons 

you can just connect it to a Insulted Redstone Conduit and match the input/output colors

**Comment by LZee** [comment]
maybe do not use actually because can not change input/output colors :)

**Comment by Thansoli** [comment]
The problem is, IMO, that the conduit switch is functionally useless right now. I've tried a number of different methods to get the CS to pass some color besides red.

![blue direct connect](https://cloud.githubusercontent.com/assets/10201672/6205183/d0e72b48-b51a-11e4-91c6-e302f7ba007d.png)

![color no pass](https://cloud.githubusercontent.com/assets/10201672/6205188/e35f3c34-b51a-11e4-8e04-c3b17c4ca1ca.png)

And yes, 6210classick is correct, I could use a vanilla lever, and pass the signal through a block before converting it to my desired color. But then I have a wall covered in vanilla switches, which just doesn't feel right with my otherwise fully automated advanced machine setup. Plus, the conduit switch has the built in activation light, no T-flipflop required! 

What I would hope to see is a bank of conduit switches imbedded in the wall, attached to my primary insulated conduit bundle which then runs off to my various machines.

![ideal](https://cloud.githubusercontent.com/assets/10201672/6205220/ceb69c2c-b51b-11e4-99e8-2153fee3cd14.png)


(Also, the yeta wrench won't let me disconnect the conduit switches from each other, as shown in that screenshot)

**Comment by evenas98** [comment]
Please add Channels!

**Comment by bhechinger** [comment]
+1

Can we please get this? that would be FANTASTIC.

**Comment by Cbert** [comment]
+1 Please add Channels.

**Comment by bookerthegeek** [comment]
Um... yes please

**Comment by HenryLoenwind** [comment]
add 50 more "me too"s and we might consider scrapping porting to 1.8.9 and implement new features instead... ;)

But to be serious: The current implementation of redstone conduits can't handle this and must be re-done first. It must be re-done anyhow, because it was never intended for more than a couple of levers or so and can be a great source of server lag when transporting constantly changing signals.

**Comment by bookerthegeek** [comment]
That makes sense. I think everybody would perfer (I know I would) if you would work on bugs and fleshing out features instead of redoing something for a version that is almost EoL.

Keep calm and chive on my good friends.
