### ISSUE TITLE
Texture and multiblock bug(Multiblock Vibrant Capacitor Bank)

### ISSUE THREAD

**Issue by Bitsnoxx** [SleepyTrousers/EnderIO#1767]
Seems to be a rendering bug with Vibrant Capacitor Banks:
![Imgur](http://i.imgur.com/U4efrVT.png)

Seems to vary depending on inventory slot.

I've also experienced some issues with Vibrant Capacitor Banks, sometimes when I place a Vibrant Capacitor Bank with the others. The max capacity is 25.000.000RF/T ignoring the other`s beside it.

Running EnderIO version: EnderIO-1.7.10-2.2.6.317
Modpack: The Dark Triology

**Comment by tterrag1098** [comment]
What is the rendering issue there? I don't see it.

**Comment by Bitsnoxx** [comment]
You have to look very close to see it on the pictures.. Maybe this will be easier to see:
![Imgur](http://i.imgur.com/56C0P8q.png)
![Imgur](http://i.imgur.com/Kfq44St.png)

Maybe try download and zoom with a photo editor?

**Comment by MatthiasMann** [comment]
That is caused by the fact that the capacitor bank is scaled down while it is rendered for the inventory. The default textures are all 16x16 - same size as the inventory slot - but it is rendered at an ~45° angle which compresses the texture.

This combined with different rounding based on rendering position causes the small border of the power bar to render differently.

**Comment by tterrag1098** [comment]
Are you sure the vibrant capacitor thing isn't just a WAILA bug? I can't get it to happen.
