### ISSUE TITLE
Item Conduit not extracting bees from Forestry Apiarist Chest

### ISSUE THREAD

**Issue by Megistus** [SleepyTrousers/EnderIO#1883]
As per title - Conduit will extract bee's from any other chest, but, not from Apiarist Chest. Probably something to do with the recent Forestry upgrade.

Minecraft 1.7.10
Forge 10.13.2.1291
EnderIO-1.7.10-2.2.8.344
forestry_1.7.10-3.4.0.7

**Comment by leagris** [comment]
forge-1.7.10-10.13.3.1403
forestry_1.7.10-3.7.0.606-unstable
EnderIO-1.7.10-2.3.0.393_beta

I stumbled upon this while driving an array of Forestry Alvearies with EnderIO item conduits and an Apiarist chest to buffer excess princesses.
I wanted princess to be automatically re-distributed to newly setup Alvearies, by pulling from this Apiarist Chest. But it still does not work.
Insertion works but not extraction.

Any chance it can be fixed in a near future?

**Comment by MatthiasMann** [comment]
EnderIO will extract items from any inventory which allows extraction - so I think this is actually a forestry issue.

**Comment by DonnerVarg** [comment]
I tried to convert some of my apiaries to use translocators and they don't work to pull from Apiarist's chest, either. I'm guessing it's a Forestry issue, but double check your chests to make sure they're public access. I know some/all of the Forestry machines can be restricted access which disables automated inventory access (tubes, etc.).
