### ISSUE TITLE
Existing Item Filter Blacklist

### ISSUE THREAD

**Issue by shadowfacts** [SleepyTrousers/EnderIO#1952]
There should be an option to use a blacklist instead of whitelist on the Existing Item Filters.

**Comment by Thansoli** [comment]
I agree with this suggestion. I had a use case for this (blacklisting a large list of items from Smeltery input), even set up a chest to store all the items so I could update the filter as needed.

**Comment by HenryLoenwind** [comment]
"Insert everything in here but things that are already in"? Does that really make sense?

I can understand having a blacklist version of every whitelist to prevent items from going somewhere else when the whitelisted target is e.g. full. But the other way around?

**Comment by wlhlm** [comment]
Are you trying to use the Existing Item Filter as a replacement for the Advanced Filter, because it has more than 10 slots?

**Comment by Thansoli** [comment]
@wlhlm: That is precisely what I was attempting. Basically, I was routing my Smeltery output *back* to the same Ender chest I was using as the input chest, which would then be sorted to the jabba barrel wall on the other side of the base. Because the barrel wall and the smelting area are not connected conduit networks, sticky mode isn't an option, either. 

Obviously, a larger advanced item filter would also be a good method for solving this small use-case. Maybe a third tier of item filter...

**Comment by HenryLoenwind** [comment]
Somehow I mixed up black and white in my head when I first answered.

The "existing item filter" is the third tier. I like to compare it with chests: You can add bigger and bigger chests, but at one point you have to stop adding slots and add a scrollbar instead. ;)
