### ISSUE TITLE
Mekanism and ender io

### ISSUE THREAD

**Issue by bdudek** [SleepyTrousers/EnderIO#2257]
the ender io gas line crashed m server
crash report http://pastebin.com/qtRFbeqK
also reported to mekanism

**Comment by Staegrin** [comment]
Same sort of problem. 
crashlog:
http://pastebin.com/4VidGf4Y

After upgrading to version 8.1 of Mekanism all gas cables were gone. Placed down an ender IO gas conduit and crashed to desktop.

**Comment by MatthiasMann** [comment]
Well - that happens if you upgrade one Mod which changes it's API without using the latest dev build of the other mod using that API (eg EnderIO).

The latest stable release of EnderIO (2.2.8) does *NOT* support Mekanism 8.x.
Work is being done in the 2.3 dev versions - but I'm not sure what the current status is.

**Comment by tterrag1098** [comment]
#2110
