### ISSUE TITLE
[Suggestion] More Item Conduit upgrades

### ISSUE THREAD

**Issue by Blood-Asp** [SleepyTrousers/EnderIO#2292]
Compared to the other conduits, the item conduits have no real upgrades. They are allready more powerfull than most other item transfer systems right from the beginning, A few Speedupgrades make them unmatched.

So how about configs for: 
Base number of items per transfer. 
Transfer increase per speedupgrade.
Changeing the ticks between transfers.

And also a new channelupgrade. So the item conduits by themself have only one color and to unlock the other 15, upgrades must be inserted.
Maybe another speedupgrade that lowers the ticks beween transfers.

That way they would scale much better and with configs everyone can decide how weak they would start and how powerfull they could become.

**Comment by MatthiasMann** [comment]
The speed upgrades are already very modular - without upgrades it is 4 items / second which I think is a good speed for the cost of the item conduits.
The ticks between transfers depends on the speed upgrades and how many items have been transferred previously. So it should also scale nicely as is.

The channels are an integral part of the conduits - and that won't change.

**Comment by Blood-Asp** [comment]
Everyone has a different opinion about the "right" speed.
The fluid conduits have a bunch of confing options to balance it but the item conduits have nothing like that so we must take them as they are.
In my experience the item conduits are so powerful, that no one even tries to use others when they are in the modpack.
As it currently stands, i will remove EnderIO from my modpack because of that. Or at last completely remove the item conduits with minetweaker.

**Comment by Xuerian** [comment]
It is an open source mod, public domain at that. You're welcome to submit pull requests or use your own fork. Not really much reason to come here and say that you're going to remove the mod from the pack you added it to if one of the devs doesn't have any desire to implement your feature.

**Comment by hisorange** [comment]
extra utilities: wireless teleport, stack / tick if needed, nestable filters, pipes cost stone+glass+1pcs redstone
translocators: moves a stack with 1 pcs of glowstone, filters are built in, fancy as hell
steve's factory: every possible feature ...
ae: almost everything or even more...
***
I can go on for pages, if the players in your modpack does only use enderio for item transportation, then that's there own fault, I like item conduits and the filter and speed upgrades feels perfectly balanced, no1 crafts a stack of electrical steel and dumps it into each and every connection because /just/, if you look at it peeps only upgrade their conduits to the level where they needed.
