### ISSUE TITLE
you may reactivate speed item duct exist in version 1.6. ... and other

### ISSUE THREAD

**Issue by wleds** [SleepyTrousers/EnderIO#2346]
you may reactivate speed item duct exist in version 1.6.

I know there are the card but I do not find this practical at all

( I also like the cost of a recipe is not configured that after the blow energy I would also like to reduce the time without reducing the energy

example:  <AlloySmelterRecipes>

  <recipeGroup name="EnderIO"> 

    <recipe name="Electrical Steel" 
       energyCost="10000"
      ( timecost="10">)

      <input>
        <itemStack modID="minecraft" itemName="iron_ingot" />
        <itemStack oreDictionary="dustCoal" />
        <itemStack oreDictionary="itemSilicon" />
      </input>
      <output>
        <itemStack modID="EnderIO" itemName="itemAlloy" itemMeta="0" exp="0.5" />
      </output>
    </recipe> )

I would also like to be able to adjust the advantage that gives octadic capacitor and other capacitor

I would also like to have a configuration file to better organize and clearer

I will make you this proposal that I love this mod these one of mod that I find the most stable :)

for any questions do not hesitate please

ps)sorry this translation is not excellent

**Comment by MatthiasMann** [comment]
Item conduits have moved to an upgrade system instead of different tiers - that won't change back. Also you only need speed upgrades at the extraction point.

An capacitor upgrade increases the amount of energy per tick which can be used by the machine - which will cause a speedup in the processing. The cost to process one item does not change at all.

**Comment by tterrag1098** [comment]
What @MatthiasMann said.
