### ISSUE TITLE
Electromagnet drops out of Baubles slot when disabled

### ISSUE THREAD

**Issue by BillH1949** [SleepyTrousers/EnderIO#2387]
Using build 375, the electromagnet can only be placed in a Baubles slot when it is enabled.  Pressing the hotkey to disable it causes the electromagnet to move to the hotbar.

**Comment by HenryLoenwind** [comment]
Yes. And what is your issue?

**Comment by eduardog3000** [comment]
I think he is expecting the disabled electromagnet to stay in the Baubles slot, which is what I would expect too.

**Comment by HenryLoenwind** [comment]
Oh, I see.

No, the magnet can only be in the slot when it's active. That's why it drops out (which is in no way a side-effect but needed special coding). That is intended to offset the advantage of using the Baubles slot instead of a rare hotbar slot.

If you want to be able to easily switch it on and off, you need to sacrifice a hotbar slot. If you don't want to block a hotbar slot, you have to pay with it by having to move it into the Baubles slot after switching it on.

**Comment by eduardog3000** [comment]
I don't like that, it makes the Baubles integration pretty useless, unless you will *never* need to disable the magnet.

**Comment by HenryLoenwind** [comment]
goes on my todo list

**Comment by eduardog3000** [comment]
HenryLoenwind#28

...

**Comment by HenryLoenwind** [comment]
Oh come on, allow me a bit of humor on my own list ;)

**Comment by Mementh** [comment]
what version of Ender IO adds the optiont to put it in the baubles spot?
