### ISSUE TITLE
Gas conduit with mekanism Crash Fixed (Mekanism v8.1 works perfect)

### ISSUE THREAD

**Issue by MrKRONIC** [SleepyTrousers/EnderIO#2437]
i updated my forge to forge-1.7.10-10.13.3.1365-1.7.10- 
then updated these mods and i no longer get world crashes from gas conduits on mekanism machines.

Mods updated.
EnderIO-1.7.10-2.3.0.372_beta
Mekanism-1.7.10-8.1.2.229
MekanismGenerators-1.7.10-8.1.2.229
MekanismTools-1.7.10-8.1.2.229

if you are running lower versions of these above i believe gas conduits wont work, but by updating these mods they will work perfect, i can provide more details if needed thanks 

Regards Luke

**Comment by jaz000** [comment]
I realise there's been a lot of enderio / Mek 8 gas conduit issues opened on both sides due to misunderstanding of which versions are supporting each other so I though I'd add my strange observations to this as I think this should work

EnderIO-1.7.10-2.3.0.377_beta (or 376 or other betas including 372)
Mekanism-1.7.10-8.1.2.229
MekanismGenerators-1.7.10-8.1.2.229
MekanismTools-1.7.10-8.1.2.229

Forge 1400 or 1388 or 1370, possibly some others

As soon as the electrolytic seperator meets the gas conduit the following happens:
you can't interract with block, inventories, items
blocks are not dropped when breaking them
mobs are no longer processed
in fact the only thing propcessed in the world is the passage of time night/day

And of course here's the real rub - this only happens in an existing world - in a new/creative world a simple setup works fine, but go into my existing world and re-create the same (isolated) setup and I get the above hang ...

any tips that might lead to working around this problem would be greatfully recieved!

**Comment by tterrag1098** [comment]
I don't see how that could be an EnderIO bug, it seems to be caused by Mekanism.

**Comment by jaz000** [comment]
Sometimes I can get everything working fine for a while but then it randomly stops working on a server or in single player it works fine until I close and re-open the map.

When it breaks I can fix this by downgrading enderio to 2.2.8.367

This combination brakes for me, just downgrading enderio fixed

EnderIO-1.7.10-2.2.8.381
Mekanism-1.7.10-7.1.2.185
MekanismGenerators-1.7.10-7.1.2.185
MekanismTools-1.7.10-7.1.2.185
Forge 1400

Mekanism might be a red herring because I want to upgrade to Mek 8 that is my goal and the reason I've been upgrading enderio

Of course it could be interraction with another mod but keeping enderio to 367 avoids the problem

**Comment by MatthiasMann** [comment]
EnderIO 2.2.8 is not compatible with Mek 8 - the build 381 works around that by disabling the gas conduits. Using an older EIO version (like 367) together with Mek 8 risks world corruption.

**Comment by tterrag1098** [comment]
"Randomly breaks" how? Do you have a crash log?

**Comment by MrKRONIC** [comment]
jaz000 your forge version is to high some mods are not compatable with the highest versions of forge

**Comment by MrKRONIC** [comment]
trust me it was enderio it states it in the crash reports

**Comment by MatthiasMann** [comment]
There is no crash report - I vote for "invalid"

**Comment by jaz000** [comment]
OK I will try and roll back forge version as far as I can

If that doesn't work I will post a "crash log" - but understand this, there is no "crash log" because it doesn't "crash" absolutely nothing is written to the log regarding this error - you will just have the log of the game running up untill that point - you can still walk around the world - you just can't interract with it.

**Comment by MatthiasMann** [comment]
Try to get a stack trace using JConsole / JStack at this point. Without any information we can't debug this.

**Comment by tterrag1098** [comment]
@jaz000 Freezing when using gas conduits is a reported problem with Mekanism on the newer forge version. I do not think we cause this...

**Comment by jaz000** [comment]
Couldn't get jstack to work yet

From jconsole the only thing which stands out (comparing working to non working) is: when game interraction stops the server thread is constantly servicing the crafter - it is not permanently static it does change occasionally.

Just a quick look around I find ~22 crafters in the world - there may be more - they have been busy!

http://pastebin.com/NDF0VpUe

**Comment by jaz000** [comment]
FWIW forge log up to the point the client was killed

http://pastebin.com/udPHDcE6

First time loading the map the client was ok - but then after quitting and saving the world and re-opening the game interraction stopped after a few seconds (This pattern very repetable in singlew player)
On exiting the game it hangs at shutting down internal server
(have to kill the process)

**Comment by jaz000** [comment]
@tterrag1098 When you say freezing reported with Mekanism - does that match :

-you can still walk around the world
-you can't interract with blocks or open inventories inventories (nothign happens)
-blocks are not dropped when breaking them
-mobs are no longer processed (they don't move)
-other block interraction like teleoprters no longer do anything

I'm getting all this while still using the last version of Mek 7 whenever I use enderio later than 367
I would appear to need to be at least forge 1384 for TConstruct to work with the new fluid registry. A complcated web of interdependencies :)

**Comment by jaz000** [comment]
Yeah sorry after much testing I've pretty much concluded this is not related to Mekanism

If I do just the following to our mod pack running on the server:
(I removed all gas conduits and electrolytic seperators for good measure)
upgrade just enderio from .367 to .381
then I can reproduce the problem above

I get the above problems with any version of enderio from .369 or later (not tested 384/385 yet ...

maybe it is something triggered by one players impressive setup with lots and lots of crafters ..
