### ISSUE TITLE
Please add a config option for teleporter speed

### ISSUE THREAD

**Issue by ghost** [SleepyTrousers/EnderIO#2442]
Waiting 10 minutes to teleport is intolerable considering these will be heavily used on our server.

**Comment by tterrag1098** [comment]
How far are you teleporting that it takes 10 minutes? That must be an exceptionally long distance.

**Comment by Haidaraaaaa** [comment]
Moving 40k blocks on X and 40k on Z was the initial plan on our server. Since then we have changed it to 5k X and 5k Z in the nether but that still takes 3-7 minutes to charge up

we have separate bases on our server so I was setting up telepads so we could all travel between them. Perhaps a maximum wait time could be set in the config?
