### ISSUE TITLE
[REQUEST] Config option to remove Inventory Panel's fluid requirement

### ISSUE THREAD

**Issue by Nova001Sol** [SleepyTrousers/EnderIO#2709]
Hi. I would like to request that you add a config option to remove the Inventory Panel's nutrient distillation requirement.

The reason is that I never really use EIO for machinery or power generation, only for item transfer. Hence why I altered the recipes of the upgrade and the panel to use vanilla items.

The thing is, while I can disable the use of the fluid in the config, I still need to make a bucket of the distillation, thus a Vat, because it still needs 2 mB to activate. Please consider this.

Thank you for reading.

**Comment by CaptiveCreeper** [comment]
You could also add a config to use rf instead of nutrient distillation.

**Comment by Nova001Sol** [comment]
It does, but it requires nutrient distillation to produce that RF.

**Comment by MatthiasMann** [comment]
The reason it uses Nutrient instead of RF is a design decision. It will not be changed to just run of RF.

And you can already reduce the running costs if you really think that the default cost is too expensive - even a single Vat with just a few zombie flesh will produce more than enough fluid to run it a long time. But as tterrag already added a cheating option ....

**Comment by tterrag1098** [comment]
@MatthiasMann "Cheating" is relative in a sandbox game :)

It's also not low cost if you consider the resource cost of the system itself, and modpacks may want to change those recipes. In the end, configurability wins.
