### ISSUE TITLE
SAG Mill produces sand with invalid metadata

### ISSUE THREAD

**Issue by Haggle1996** [SleepyTrousers/EnderIO#2751]
When grinding items that produce sand (gravel, glass, etc.), the sand output has a metadata ID of 32767. I've tried overriding the output using either SAGMillRecipes_User.xml or OreDictionaryPreferences_User.xml (by adding an itemMeta="0" to the stack), but this does not change the output.

I've also noticed that outputs in the Core.xml files are not being followed. For example, the SAG mill does not output flint ever, even though it's in the output list.

Most recently tested using 2.3.0.407, but this problem has been around for a bit.

**Comment by srs-bsns** [comment]
I am using a custom user.xml for the SAG mill to fallow other mods progression from stone->cobble->gravel->sand so I can't properly test with just the vanilla core.xml, but I don't have any problems with sand beng created with erroneous meta data.. all sand I see has a proper meta data of 0.

The flint problem, however, does exist and is related to #2726 except with the core.xml entries for gravel instead of the grinding balls. The entries use 'flint' and not 'itemFlint'.

Note: the example code at the start of the file should also be updated to 'itemFlint' as well. :)

**Comment by Keyarose** [comment]
I am also getting the bad metadata when making sand with the SAG mill.  While it can still be smelted into glass, it is unusable for making AE2 quartz seeds(probably specifies metadata 0 in the recipe for some reason).
Using: 
EnderCore 0.1.0.22beta
EnderIO 2.3.0.412beta

**Comment by axelpx** [comment]
Same issue here, SAG mill produce sand with metadata value.

**Comment by mmelvin0** [comment]
FYI, 32767 == OreDictionary.WILDCARD_VALUE

You MAY (I haven't tested) be able to work around this by adding sand to OreDictionaryPreferences_Users.xml and specifying the actual item (e.g. not from the ore dictionary.)

**Comment by rastamanfb** [comment]
I can also confirm that I am getting this issue.
I have previously reported it to the creator of The 1.7.10 pack who has advised to report it here.
I would imagine if its having issue with flint and gravel there are wider problems

Kind Regards

**Comment by leagris** [comment]
It is also grinding cobble into Invalid OreDictionary name gravel.
