### ISSUE TITLE
Can't load my world with newest release because of crash!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [SleepyTrousers/EnderIO#2757]
Log: http://hastebin.com/abojububag.coffee

**Comment by JillSwift** [comment]
Ditto, 2.3.0.411

http://pastebin.com/rg7BCmzq

**Comment by srs-bsns** [comment]
I can confirm that this is happening. It's related to the Dimensional Transceiver.

Likely commit in which the bug was introduced: 9320c00618a8ce30ba91bac0cdf1757df2534ec5

After updating from build 408 to 412 I was unable to load my world until I loaded it in MCEdit and removed some Dimensional Transceivers. Loading the game afterwards and replacing the Dimensional Transceivers the game would crash again when adding a channel to the 'Send' list of the Power tab. (Note: The channel's name in the 'available' list would disappear just before crashing.)

In addition to crashing, ~~I am unable to create private channels.~~ Any private channels created will not show up in the 'available' list, though they do exist. (Confirmed by downgrading back to build 408 and the privated channels magically appeared.)

It would seem that array to store the channel names is not being formed properly in some circumstances, but I didn't look at the code long enough to confirm if this is the case.

**Comment by tterrag1098** [comment]
Could any of you provide your dimtrans save file json? I can't reproduce this.

**Comment by srs-bsns** [comment]
Sure. Here's the .json in my save:

```
[
  {
    "name": "Priv Main Power",
    "user": "df5a94d0-68f1-3d69-907f-401aeeff28f7",
    "type": 0
  },
  {
    "name": "Main Power",
    "type": 0
  }
]
```

This data is the same before and after crashing, but as I said in my previous post, private channels aren't showing up in GUI's 'available' list, so in-game I can't see 'Priv Main Power' (which I added using build 408).

Other than private channels not showing up, Everything seems to work fine until I try to add a public channel to the 'Send' list for power.

Additional notes:
1. adding a channel to the 'receive' list for power does not crash the game.
2. The dimensional transceiver has to be powered for it to crash.

 I didn't test channels for items (yet), but only because it's sucks having to keep reloading the game with 140+ mods. I'll try creating a new world with just EnderIO/Core and a few essentials and recreating.

**Comment by tterrag1098** [comment]
Found it, stupid mistake.

**Comment by srs-bsns** [comment]
Awesome. I was just going to give you a new update, but no need now.

Cheers bro. :)
