### ISSUE TITLE
Item Conduit Speed Upgrade Insert

### ISSUE THREAD

**Issue by MrKrabat** [SleepyTrousers/EnderIO#2823]
Hello,
as the wiki page says http://wiki.enderio.com/Item_Conduit_Speed_Upgrade the speed upgrade should be usable for the insertion or extraction speed.
The insert mode of the item conduit have no slot for the speed upgrade.

My ender quarry is too fast for the conduits, it filters netherrack and ash into the trashbin (priority is higher than the chests) but not all netherrack and ash gets deleted and it fills the chests.

The trashbin delets instantly, adding more filters to the trashbin reduce the amount of filtered items which reach the chests.

Using EnderIO 1.7.10-2.3.0.415 beta

Is it intended that a speed upgrade is not possible for the insert mode?

**Comment by tterrag1098** [comment]
Insert has no speed limitations, it will insert items as they are pushed to it.

**Comment by MrKrabat** [comment]
I've expected this answer,

i think the Ender Quarry push all the items at the same time in the conduit, the conduit push the first item in the trashbin. The problem is the trashbin have just "one slot", so the conduit think this slot is already used, because it just put a item in the only available slot. Or the trashbin isn't instantly and need the next tick to delete its content.

The easiest fix would be adding more inventory slots to the trashbin.
I can't remember this behaviour in the past, but this isn't a bug and can be closed :)

**Comment by wlhlm** [comment]
@MrKrabat You could attach an inventory (chest etc.) directly to the quarry and have the conduits pull from that. You can attach the conduits to multiple sides and increase (multiply) extraction speed that way.

Here's an example setup using Enhanced Inventories' Locker (which is a just chest that combines vertically instead of horizontally like vanilla chests):
![2015-09-19_02 27 34](https://cloud.githubusercontent.com/assets/1928113/9973597/41c5c0ea-5e76-11e5-83a1-bff6ad9ef8d4.png)

I don't think there are any throughput limitations for Quarry → Inventory.

I've never had performance problems inserting into a trashbin.

**Comment by MrKrabat** [comment]
@wlhlm This is my setup and only the first item in the filter is deleted for 99% sure

![2015-09-19_14 12 22](https://cloud.githubusercontent.com/assets/8700513/9976146/c5fd5562-5eda-11e5-90a4-ab2c77641535.png)
![unbenannt](https://cloud.githubusercontent.com/assets/8700513/9976159/28aa4b48-5edb-11e5-967e-5df027f59d96.PNG)
