### ISSUE TITLE
NullPointerException in DarkSteelController

### ISSUE THREAD

**Issue by MrNuggelz** [SleepyTrousers/EnderIO#2861]
http://pastebin.com/pvG8nXG0

**Comment by HenryLoenwind** [comment]
see #2780

**Comment by MrNuggelz** [comment]
Seems that the nullpointer comes if i use the glider of my armor. At that moment all the player on the server that don't have an enderio armor get that error. I think it has something to do with the UUID.

**Comment by HenryLoenwind** [comment]
This comes when there are clients logged in that don't know about your player. Ender IO sends a notification about your status change to all clients (so they can render your character correctly), but some of those don't know about you...and crash.

I believe the root cause is a difference between a vanilla/forge server and some of the other servers out there. Vanilla/forge always tells all clients about all players, the others only about other players within render distance.

However, as long as tterrag doesn't pull my proposed fix, we will never find out if I guessed correctly.

**Comment by MrNuggelz** [comment]
Then i will try build with your changes in it
