### ISSUE TITLE
Unexpected results when painting travel anchor in painting machine

### ISSUE THREAD

**Issue by LyraelRayne** [SleepyTrousers/EnderIO#2902]
If you paint the travel anchor to look like a painting machine, its icon becomes this!
![image](https://cloud.githubusercontent.com/assets/11632412/10427839/90c3fd18-7138-11e5-882e-d48fcb118e11.png)

Secondly, placing the block renders the wrong sides. For example my "Painting Machine" has the front facing the ground. 

![image](https://cloud.githubusercontent.com/assets/11632412/10427916/24e2d0fa-7139-11e5-9390-a5fa186d0a3f.png)

Painting the travel anchor to look like Thermal Expansion Redstone Furnace gives this nice little result. I kinda like it, but it probably isn't what should happen. 
![image](https://cloud.githubusercontent.com/assets/11632412/10427928/464f40a2-7139-11e5-8586-16765232547f.png)

This was all done in the obscurity modpack so I haven't ruled out this being an interaction bug but I'm fairly confident this will be reproducible standalone. Might try and reproduce it that way tomorrow. Bed time for me right now!

**Comment by HenryLoenwind** [comment]
(1) Bad item rendering: I'll have to look into that

(2) Bad rotation: Halfway fixed, machines will now render upright but always facing south. Unless there's a good usecase for having fake machines around it'll stay that way. (just too much work)

(3) That is intentional on TE's side. Their renderer won't render their block's look onto anything else. You'll see the same thing when using one of the frame mods on TE machines.
