### ISSUE TITLE
Some machines almost always invisible

### ISSUE THREAD

**Issue by Mawwz** [SleepyTrousers/EnderIO#2975]
Through googling around, I've come to understand that this appears to be an issue when Optifine is installed, which I am currently using. I could only find one other issue report regarding something similar with a Combustion Generator.

However, I have observed the following:

- Full block machines such as the SAG Mill and the Alloy Smelter appear fine
- Machines similarly colored to the SAG Mill/Alloy Smelter which are not full blocks (The Vat, Farming Station, Combustion Generator, etc.) do go invisible
- Obelisks and the Enchanter do not go invisible

Without any real knowledge of how Minecraft mods work, this leads me to believe the issue lies within the transparent parts of these "Dark Blue/Green" colored non-full-block machines.
I hope at least some of this is new information, and that it helps solve this conflict between mods.

**Comment by wlhlm** [comment]
EnderIO does not support Optifine. (There is not a lot that can be done about that, since Optifine messes with Minecraft's rendering in major ways, but is closed source). If you get rendering issues, remove it.

That said, most rendering problems go away if you set the Chunk Rendering to "Default" (instead of Multi-thread or Source).

More info in [#2862 (comment)](https://github.com/SleepyTrousers/EnderIO/issues/2862#issuecomment-150161935)

**Comment by Mawwz** [comment]
Thanks for the reply and the info. It's a shame about Optifine, but setting Chunk Rendering to Default did fix my invisible machines issue.

**Comment by HenryLoenwind** [comment]
Yes, the closed source part of it is whet's stopping us from supporting it. We just have no idea what to do differently for Ender IO to work with Optifine.

And BTW, the difference you noticed is that full blocks are rendered by Minecraft's renderer, while all other shapes are rendered by our code.

**Comment by tterrag1098** [comment]
@HenryLoenwind It's due to Optifine threading the chunk rendering which totally breaks our assumption of the render pass being statically accessible. This is why disabling threaded chunk rendering fixes it.
