### ISSUE TITLE
World Crash

### ISSUE THREAD

**Issue by gamecraft45** [SleepyTrousers/EnderIO#2986]
Server crash on start when loading world.

http://pastebin.com/JJWEYnqa

**Comment by HenryLoenwind** [comment]
What happens here is that a thermaldynamics block is not checking its te correctly. The te is gets is by chance an Ender IO one, but Ender IO is not involved otherwise in this crash.

To all mod authors: Check the result of getTileEntity() before casting it. Always. Better check it twice, too. It max be your te, it may be a Mayan calendar with all Mondays marked crossed out with red ink.

**Comment by tterrag1098** [comment]
Actually one should never need to check the TE, it should be guaranteed that a block has the TE it wants when it exists in the world. Vanilla makes this very clear. Something else is going on here.

**Comment by mindforger** [comment]
it's a KCauldron Server ... knowing that it deals sometimes a bit unconsequent i'd say it's a non fixable issue because of modified API behaviour

**Comment by XFactHD** [comment]
This crash could also be caused by forge changing block IDs in the curse of a mod update.
@gamecraft45 did you recently update any mods?

**Comment by HenryLoenwind** [comment]
@tterrag1098, if you look through the issues of the last half a year, you can easily find a dozen ones where there was a wrong te. So this is happening a lot nowadays. If it is some kind of work corruption, or some mod messing with blocks (frames?), or whatever, I don't really care---not checking leads to a world that cannot be loaded at all.
