### ISSUE TITLE
Crash with latest EnderIO beta (420) and Modular Powersuits

### ISSUE THREAD

**Issue by ericcotelnu** [SleepyTrousers/EnderIO#3025]
[crash-2015-11-21_21.00.26-client.txt](https://github.com/SleepyTrousers/EnderIO/files/40966/crash-2015-11-21_21.00.26-client.txt)

Attached crash log

**Comment by Badcholo** [comment]
https://github.com/QMXTech/MachineMusePowersuits/releases
Scroll down till you see these 3 files.
Numina-0.4.0.7-QMX.jar
ModularPowersuits-0.11.0.7-QMX.jar
ModularPowersuitAddons-0.11.0.7-QMX.jar
Download, install, enjoy. verified works on cauldron, 1492.152

**Comment by HenryLoenwind** [comment]
Badcholo, why do you recommend downgrading to a version that is 9 months older than the current one?

**Comment by HenryLoenwind** [comment]
ericcotelnu, please have a look in your logfile, there must be another error in there. This is just the final crash. (eio is also marked UE)

**Comment by Badcholo** [comment]
Cause it has the same content and the updated(or so called) version has crashed and corrupted my server worlds several times now. I don't know what it is about it.

**Comment by mindforger** [comment]
@Badcholo `Download, install, enjoy. verified works on cauldron, 1492.152` you know your world is mostly possible corrupting BECAUSE of cauldron ... also you snipped the important part of your crash log where the environment is described, don't ever do that, it's not helping! ... 
and i bet there is a cauldron or kcauldron used in that crashlog ... you need to understnad that caudron is doing plenty stuff and plenty of it in multithread .. and that MOST mods are not aware of that .. so a mod causing world corruption while using caludron simply is happening because almost NO mod officially supports cauldron
try to repeat your issue without any unsopported stuff

**Comment by Badcholo** [comment]
I didnt' create this issue. I also didn't post any crash logs and i don't have any issues with cauldron or corrupt worlds unless i'm constantly installing and removing new mods without deleting the world. In the future please pay attention to who and what is going on before you start assuming i don't know what i am doing. I have test servers that i do all my work on and intensively test and run compatibility checks on mods before i put them into my online server. My initial testing happens on a  client with just forge and this mod has not passed that point with corrupt SSP worlds and crashes.

**Comment by SvEgiiVEteR** [comment]
http://hastebin.com/sivaqeduno.md
I also have a crash but with the latest version ..

**Comment by Badcholo** [comment]
Wow that is a lot of mods

**Comment by HenryLoenwind** [comment]
And again, this is just modular powersuits crashing because Ender IO could not be loaded. The reason why Ender IO could not be loaded is not in the crash, it's in the logfile. Please post that one, too.

**Comment by Badcholo** [comment]
i might go get this mod and make my server crash just so i can get you log files when i get home.
I'd like to see what is really going on.

**Comment by SvEgiiVEteR** [comment]
http://paste.ubuntu.com/13478757/
Here the log file)

**Comment by HenryLoenwind** [comment]
@SvEgiiVEteR The file "2_5_screwdriver-2.4.2.jar" contains an old version of Ender IO's Tool API. Get the author to update or manually remove the API from the jar.

For the other crashes: There may be other mods out there which come with outdated APIs. If you enable debug logging, look for things this:

```
[21:17:20] [Client thread/DEBUG] [FML/]: 	EnderIOAPI|Tools(API: EnderIOAPI|Tools:0.0.1): 2_5_screwdriver-2.4.2.jar ()
```

Here you see that an Ender IO API is loaded from another mod's jar file. This is ok, as long as it's the same version that all other mods that are installed are expecting. Sadly FML is a bit dumb here, because it could do that check automatically:

```
[21:17:15] [Client thread/DEBUG] [FML/]: Found API crazypants.enderio.api.tool (owned by EnderIO providing EnderIOAPI|Tools) embedded in screwdriver
[21:17:15] [Client thread/DEBUG] [FML/]: Found API crazypants.enderio.api.tool (owned by EnderIO providing EnderIOAPI|Tools) embedded in EnderIO
```

**Comment by tterrag1098** [comment]
The hell is he shading our API for...

**Comment by SvEgiiVEteR** [comment]
It may be the case. but 0.11.0.283 works

**Comment by MJRLegends** [comment]
So whats the best solution for this without having to use crappy versions of MachineMusePowersuits

**Comment by MJRLegends** [comment]
See my reference for more information on this

**Comment by Xen1290** [comment]
@SvEgiiVEteR  Build 284 of ModularPowerSuit was broken, try with 289, it's fixed. Also, build 289 contains ModularPowerSuit Addons integrated. And, if you are upgrading to 289, backup and reset your machinemuse config folder. See https://github.com/MachineMuse/MachineMusePowersuits/issues/653 for more informations.
