### ISSUE TITLE
Item conduit dont work in 2.3.0.420_beta

### ISSUE THREAD

**Issue by Derweis** [SleepyTrousers/EnderIO#3035]
when connected to gregTech machines are not working. I tested on different sides . Pictured above settings, but does not move tetrahedrit ore.

![2015-11-24_13 09 03](https://cloud.githubusercontent.com/assets/15996927/11363706/9a02a10a-92ac-11e5-803a-d52bbd5b1609.png)
![2015-11-24_13 09 09](https://cloud.githubusercontent.com/assets/15996927/11363708/9a0517fa-92ac-11e5-9f83-dd86ca68a1d0.png)
![2015-11-24_13 09 14](https://cloud.githubusercontent.com/assets/15996927/11363709/9a081144-92ac-11e5-96ef-26bdce9f2c87.png)
![2015-11-24_13 09 16](https://cloud.githubusercontent.com/assets/15996927/11363707/9a042a70-92ac-11e5-924f-d551e485ff6a.png)

RU/При подключении к машинам gregTech не работают. Тестировал с разных сторон. На картинках показал настройки, но tetrahedrit ore не перемещается

**Comment by Badcholo** [comment]
RU/При подключении к машинам gregTech не работают. Тестировал с разных сторон. На картинках показал настройки, но tetrahedrit ore не перемещается
Translated......................................
RU / When connecting to machines gregTech not working. I tested on different sides . Pictured above settings, but does not move tetrahedrit ore

**Comment by Derweis** [comment]
и?

**Comment by Derweis** [comment]
@Badcholo и?

**Comment by Badcholo** [comment]
I was just translating for those who might think it's more information.

**Comment by MatthiasMann** [comment]
does it work from chest to chest, can a hopper insert into the GregTech machine, did it work with an older version of either EnderIO or GregTech?

**Comment by Derweis** [comment]
Yes, it works

**Comment by adudney** [comment]
You're trying to bend an ore.

GT machines don't allow input from automation when there isn't a valid recipe using that item. So since inserting an ore into a bending machine will do absolutely nothing, the machine rejects the input, thus the ore never leaves the chest.

Try it with an ingot, it should work fine then (And you'll also need the integrated circuit for it to actually process, but you should be able to insert the ingot anyway.)
