### ISSUE TITLE
Inventory Panel displaying/pulling wrong items

### ISSUE THREAD

**Issue by Cuppycake** [SleepyTrousers/EnderIO#3101]
Inventory will show searched item but export different item(s)
Example:
Typed in hardened to find hardened blood shard
GUI shows hardened blood shard and amount
I click to pull shards out and instead BC Kinesis pipes come out

I dont believe its an issue with the mod items Im pulling out as this has happened dozens of times 
with very random items from all sorts of mods.

**Comment by MatthiasMann** [comment]
Can you reproduce that in single player? And what steps are required to get this?

**Comment by Cuppycake** [comment]
Haven't tried yet Ill test shortly. 
Nothing special has to happen. I at any time go to my panel grab the item I want and before
it gets into my panel even it changes into a random item.

http://imgur.com/a/zcLiy

Here is some screen shots that just occurred on my server. It's not those specific items though as its happened numerous times with items of all types.

**Comment by Krhymez** [comment]
This happens randomly. Players are also reporting in the the pack i created.
There seems to be multiple issues with the inventory panel currently.
-Pulled item is not the item you receive (like shown above)
-Inventory panel sometimes not using Buckets of liquids in crafting recipes, it will return the full bucket back to you.
-Items randomly disappearing/getting deleted

**Comment by jaquadro** [comment]
I didn't realize EIO had already embedded support for Storage Drawers.

My guess is that EIO is either doing some level of caching that doesn't like how the order of slot enumeration changes, or it's mixing up "drawer" slots and "inventory" slots.  I kind of suspect that later.

I'm happy to answer more questions about drawer internals.

**Comment by jaquadro** [comment]
Sorry, I realized drawers aren't actually mentioned anywhere in this issue specifically.  I just got linked here related to it.  Ignore the above if not relevant.

**Comment by MatthiasMann** [comment]
Well - even if the indices got mixed up - I don't think this could be the cause here.

The inventory panel assigns an unique ID per item (on the server) which depends on the item ID, meta data and NBT tag. Server and client use this to communicate the item lists and requests.

On extracting the server verified that the item in a specific inventory/slot is what the server expects before extracting.

I assume that this is a kcauldron issue (as I think all reports had that in common) and the item IDs are not the same on server and client. If someone sees this issue on non kcauldron servers this information would be really helpful in combination with the logs generated by the debug build linked in #3129.

**Comment by Cuppycake** [comment]
I can say for a fact that this issue is also present on a friends FTB Infinity server running straight forge.

Two people on that server experience the issue with drawers and I on my server experienced it using iron chests

**Comment by HenryLoenwind** [comment]
"your server", @Cuppycake ? Does that mean you control it? If so, would *you* please use the test version that is linked in #3129 and send us the logs?

**Comment by Cuppycake** [comment]
Yes I own and maintain the server and the pack on all my own hardware. Ill see what data I can gather.
