### ISSUE TITLE
ME conduit connection weirdness

### ISSUE THREAD

**Issue by headkandi** [SleepyTrousers/EnderIO#3150]
Hello! My dense ME conduits do not want to connect to regular ae glass cables. It can be related to the issue #3056. I've already updated Ender IO to the build 423 but the weirdness keeps happening. Here is the screenshot:
http://i.imgur.com/89P092i.png

As you can see, gaping happens only with dense conduits, regular ones do fine in this setup. And also, which is more interesting, it happens only when:
There is another possible direction to connect which is disabled using the yeta wrench.
This disabled possible connection is with a glass cable, not an other conduit.

Hope it helps, thank you!

**Comment by HenryLoenwind** [comment]
That pic is a bit packed, could you mark the spot you're talking about?

**Comment by headkandi** [comment]
Sure! http://i.imgur.com/015xlLL.png

**Comment by headkandi** [comment]
Actually, this isn't the first time I'm facing this kind of bug. And, as I can remember, it was always with the conduits that were unconnected from any classic ae cables (including dense ones) - using the Yeta wrench.

**Comment by HenryLoenwind** [comment]
Ok, so it is what I suspected when looking at the pic the first time. The conduits are trying to connect but the AE2 cable doesn't connect back.

Did you notice if the direction of the disabled connection makes any difference? Is it only the opposite side? (Common problem with connecting block is that one block's UP is the other block's DOWN.)

**Comment by headkandi** [comment]
I'm not sure but it can be it. This is another problematic node:
http://i.imgur.com/KglZO59.png
It doesn't transmit signal to the smart cable and its opposite side is being unconnected from the glass cable.

**Comment by headkandi** [comment]
Oh and btw if I remove conduit and place it back, it's all fine even if I reinit network. Until Minecraft restart. And also it's not only me cables but also energy cell and any block me conduit can connect to.I guess.

**Comment by headkandi** [comment]
Update! When I place AE cable anchor at that opposite Yeta-unconnected place, the conduit connects immediately and everything works just fine.
http://i.imgur.com/vvO4W68.png

**Comment by HenryLoenwind** [comment]
The working fine on (re-)placing the conduit could be caused by either the conduit forcing the connection (we do that in some places, see history of ME conduits) or the cable connecting before the conduit leaves "connect to everything" mode.

And about the anchor, I'm not sure if the conduit looks differently to the cable for "connection disabled" and "no connection because cannot connect". But in any case, that should not effect the opposite side.

At the moment, I tend to blame the cable. Conduits are usually pretty good in reflecting their internal state in the rendering, so rendering the connection means that it also signals that to the cable. However, I'm not the expert on ME conduits nor the AE2 API and may be wrong here.

Give this a day or two for tt and mm to have a look, too.

**Comment by headkandi** [comment]
Okay, thank you for looking into this! Anyway, this won't be that big problem for me anymore since I know those details about where and when it happens. Just a few more anchors around the base and I'm fine, hehe.
Have a nice day and thanks for the amazing mod!

**Comment by tterrag1098** [comment]
Have you tested this in the latest builds?

**Comment by headkandi** [comment]
It's been a long time, sorry about that :)
I was playing in the same world at july and september, i think i was using more recent version of enderio. I haven't tested it but i don't remember facing this kind of problem once. I guess you fixed it, guys.
