### ISSUE TITLE
Bug : TileConduitBundle cannot be cast to TileHyperCube

### ISSUE THREAD

**Issue by Lorenzo77** [SleepyTrousers/EnderIO#3172]
hello,

first, thank's for EnderIO, this mod is perfect, i like all the machinery, the armor and tools and on the top, the conduits, they are so easy to use and very powerfull !

i'm in a big trouble, my favorite world where i spend a lot of time building massive tech is now crashing during the load ... i don't want to loose all my work.

this is the report : http://pastebin.com/rcjtnZNS

my world use a personnel modpack with some modified config files but all was ok until today.

**Comment by HenryLoenwind** [comment]
see #2835

**Comment by Lorenzo77** [comment]
i already try to update with the last version and i have the same bug :
EnderCore-1.7.10-0.2.0.31_beta.jar
EnderIO-1.7.10-2.3.0.423_beta.jar

http://pastebin.com/12k68G0A

**Comment by wlhlm** [comment]
Yes, that is to be expected. The Pull Request @HenryLoenwind linked isn't merged yet (and it looks like the code has to be revisited). It means that the issue is known and a fix is being worked on for the next stable release, no need to have multiple issues open for the same problem.

**Comment by Lorenzo77** [comment]
ahhhhh ... ok, i didn't undestand this ^^
i will wait for the update then.

**Comment by HenryLoenwind** [comment]
I think I need to write this down clearly here, no way to piece this together any other way now:

Since about September last year, some unknown mod started corrupting worlds. The symptom is that blocks and their tile entity (read as "extended data like chest content") no longer match. The result is a crash.

I linked that PR because it has become a "central hub" where all reports of this kind are linked in. Not because it fixes the corruption. It in fact only stops the crash itself and leaves the corrupted blocks in a completely useless state---not crashing, but not working either.
