### ISSUE TITLE
Teleporter Range is Unproportional.

### ISSUE THREAD

**Issue by TheChromeCrafter** [SleepyTrousers/EnderIO#3190]
Teleporting up works properly, I assume, and the teleporter block aiming down has less of a range.

Ex of Up range being proportional. **http://i.imgur.com/nH7oGol.jpg**
EX Of Down range not working. **http://i.imgur.com/FNcBBmJ.jpg**

If I am doing something incorrectly, I would love input.

**Comment by CyricV** [comment]
If this is at the absolute range limit this could be due to you being one block closer to target when on the lower anchor and one further away when you are on the upper anchor. Assuming the range is calculated from your person to the target anchor as opposed to between the anchor you're on to the target anchor.

**Comment by tterrag1098** [comment]
That's exactly what's happening. I don't personally think it's an issue, as physically you ARE closer to the upper teleporter when standing on the bottom one than vice versa.
