### ISSUE TITLE
Crash on joining world

### ISSUE THREAD

**Issue by drewbit** [SleepyTrousers/EnderIO#3227]
#### Issue Description:
Crash upon trying to join world (On server)

#### What happens:
On loading into the server the game crashes
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.8.9-3.0.0.10_alpha
- EnderCore: EnderCore-1.8.9-0.3.0.10-beta
- Minecraft: 1.8.9
- Forge: 1.8.9-11.15.1.1764

#### Your most recent log file where the issue was present: 

http://paste.ee/p/t4atY

**Comment by mindforger** [comment]
how do you assume this is enderio's fault ?

`com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: com/rwtema/denseores/modelbuilder/ModelBuilder
` 
there is something utterly wrong with your modpack

what the heck is `mezz.jei.ProxyCommonClient.startJEI`

and the rest looks like an infinite loop of calls, maybe a filter inside a filter doing an infinite loop crashing your client at some point

can you upload the crashlog instead of the ordinary log ?

**Comment by drewbit** [comment]
.. You know I have absolutely no idea why I originally thought this was on the side of EnderIO. It was 100% DenseOres being funky. 

No idea what the ProxyCommonClient is though..

Well sorry for wasting your time, thank you very much for pointing me at the right thing though!

**Comment by Cracks777** [comment]
where are the 1.8.9 enderio builds?

**Comment by wlhlm** [comment]
There are none. See #3130.

**Comment by wlhlm** [comment]
http://ci.tterrag.com/job/EnderIO-1.8/
http://ci.tterrag.com/job/EnderCore-1.8/

**Comment by Cracks777** [comment]
thanks.
