### ISSUE TITLE
Magical Crops Hoe not accepted in Farming Station

### ISSUE THREAD

**Issue by Smalfinn** [SleepyTrousers/EnderIO#3239]
#### Issue Description:
Im using magical crops to grow resources and wanted to use enderIO's farming stations to auto farm the crops, I found that magical crops infused essence tier 3 hoe is unbreakable, perfect I thought, until I tried to add it to the hoe slot in the farming station and the station wont accept it.

#### What happens:
I try to place the hoe into the farming station but it wont accept it.

#### What you expected to happen:
I expected the farming station to just accept the hoe and begin to hoe the farm land.

#### Steps to reproduce:

1. Have a Magical Crop Infused Essence Hoe Tier 3
2. Have a Farming Station
3. Try and put the hoe in the station

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 2.3.0.423-beta
- EnderCore: 0.2.0.31
- Minecraft: 1.7.10
- Forge: 1.7.10-10.13.4.1614

#### Your most recent log file where the issue was present: 

https://gist.githubusercontent.com/Smalfinn/d2f14ba6a5b5cd6c67e8/raw/8b54c7c01b0a3b63e560466e745f76306717b29b/gistfile1.txt

**Comment by wlhlm** [comment]
EnderIO supports [_some_](https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/config/Config.java#L311) Hoes from Magical Crops:

```java
      "magicalcrops:magicalcrops_AccioHoe", "magicalcrops:magicalcrops_CrucioHoe", "magicalcrops:magicalcrops_ImperioHoe",
      // disabled as it is currently not unbreaking as advertised "magicalcrops:magicalcrops_ZivicioHoe",
```
The thing is, the Farming Station has to rely on a whitelist of items that work as Hoes due to the way they are implemented in Minecraft, thus there will always be some Hoe that's not supported.

The whitelist can be edited in the in-game Mod Settings menu under "Farm Settings" -> "farmHoes".

What is the Item ID of the Infused Essence Hoe (you get it by pressing <kbd>F3</kbd>+<kbd>H</kbd> and hovering over the item in the inventory)? Can you manually add the Hoe to the whitelist and test if it doesn't break the game or anything (check whether the Farming Stations stops once the durability of the Hoe has run out)?

**Comment by tterrag1098** [comment]
The reason that hoe is not supported is because it is not damageable. I would rather not support undamageable hoes out of the box, to me that is a balance concern. You are of course free to add it though, as @wlhlm has pointed out.

**Comment by Smalfinn** [comment]
Okay well I tested it by changing the config but it broke anyways.

**Comment by spannerman79** [comment]
@tterrag1098 https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/config/Config.java#L311 will have to change (or have added to) the following since Magical Crops 4 beta 5;

` "magicalcrops:magicalcropsarmor_AccioHoe", "magicalcrops:magicalcropsarmor_CrucioHoe", "magicalcrops:magicalcropsarmor_ImperioHoe", `
