### ISSUE TITLE
Dedicated Server Crash - Exception in Server Tick Loop

### ISSUE THREAD

**Issue by sdaddy** [SleepyTrousers/EnderIO#3258]
#### Issue Description:
Trying to update from 1.8.9-3.0.0.18 to 1.8.9-3.0.0.21

#### What happens:
Server crashes on startup.

#### What you expected to happen:
Server to start normally. :stuck_out_tongue:

#### Steps to reproduce:

1. Start server.
2. Server crashes.
3. Profit???
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.8.9-3.0.0.21
- EnderCore: 1.8.9-0.3.0.13
- Minecraft: 1.8.9
- Forge: 11.15.1.1808

#### Your most recent log file where the issue was present: 

http://pastebin.com/raw/dqWs5jf7

**Comment by sdaddy** [comment]
I'm confused why this was closed with no response.

**Comment by HenryLoenwind** [comment]
Because we are not _supporting_ unreleased **unfinished** versions of the mod. While I don't go as far as to ignore those reports completely, every minute I spend on writing responses is 2 minutes the 1.8.9 version will be delayed, and every hour I spend doing things out of order is 3 hours the port will be delayed.

Feel free to stress-test the mod to its fullest...once we release a public (read: on curseforge) version. At the moment, it just feels like:

![](http://i.imgur.com/PlwdPqe.png)

About your report: Yes, we had 2 builds that just won't run on a server at all. That happens when I finish at 3 am to get some sleep before I have to get to work in the morning and skip doing a full (~30-45 minutes!) cycle through my test worlds.
