### ISSUE TITLE
Server crash with EnderIO Please help

### ISSUE THREAD

**Issue by Dartherez1234** [SleepyTrousers/EnderIO#3278]
#### Issue Description:
So i made a modpack to play with 2 of my friends with and i keep getting these crashes on my server

#### What happens:
After afew minutes of the server being up the server just crashes, ive noticed that everytime i crash it is when i am near or attacking a wither skeleton which apparently according to WAILA is from EnderIO so thats what brought me here 

#### What you expected to happen:
I expected for the server to carry on with normal activity instead of crashing

#### Steps to reproduce:

1. Get on the server
2. Play for a few minutes
3. Kablam you have a crash
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.7.10-2.3.0.424_beta
- EnderCore: 1.7.10-0.2.0.33_beta
- Minecraft: 1.7.10
- Forge: forge-1.7.10-10.13.4.1614-1.7.10

#### Your most recent log file where the issue was present: 
Latest Log: https://gist.github.com/Dartherez1234/03104b895bb4d90804040f572b03e135
Crash Report: http://pastebin.com/GY8Rb137

**Comment by HenryLoenwind** [comment]
What makes you think this is related to Ender IO?

**Comment by VT-14** [comment]
There is a config to turn off Ender IO's replacement of Wither Skeletons.  See if changing that to false fixes it.

The log ends with over 200 of the following line.  You might want to look at MFR as well.
[Server thread/DEBUG] [MineFactoryReloaded/MineFactoryReloaded]: [IMCHandler] %s from %s

**Comment by Dartherez1234** [comment]
Thanks for the help really apprecate it will have a look at MFR for you see if anything is wrong

**Comment by VT-14** [comment]
I don't have any reasonably sound ideas.  I'm not a programmer, just someone who has tried making my own personal modpacks and found some things to look for in crash logs.  You should probably poke a programmer from MFR and ask if that repeating line until crash (server log) is as incriminating as it seems.

Since you mentioned Wither Skeletons, are you spawning them in with an Auto-Spawner?  If you are, then try adjusting Ender IO's Wither Skeleton replacement in the config, and get a new skeleton (I have no idea what will happen to the one in that safari net).

**Comment by HenryLoenwind** [comment]
9 days? Closing. Hope you could fix your problem.
