### ISSUE TITLE
Could not spawn mod entity ModID: EnderIO EntityID: 6

### ISSUE THREAD

**Issue by Schaamlipman** [SleepyTrousers/EnderIO#3284]
#### Issue Description:
Playing RR3 modpack. Went to nether and saw a fortress, connection got ended when approaching the fortress. I'm playing on a MP server so can't get serverlog at this moment. Clientlog gives this line: 
java.lang.RuntimeException: Could not spawn mod entity ModID: EnderIO EntityID: 6 at ( 466.03125,66.0, -627.53125) Please contact mod author or server admin.

#### What happens: disconnection from server. no clientcrash.

http://paste.atlauncher.com/view/8c981c26

**Comment by HenryLoenwind** [comment]
If I had to guess (and I have to, with that little information to go on), I'd say you are not interested in getting help because you ignored most of the report template.

Nevertheless, that message usually indicates that the number of entities (mobs) that are registered on the server and on the client differs. Check the config for any mod that registers entities and make sure they are the same on server and client.
