### ISSUE TITLE
Allow outputing input tank from Vat.

### ISSUE THREAD

**Issue by thomas15v** [SleepyTrousers/EnderIO#3319]
![vat_bug](https://cloud.githubusercontent.com/assets/2163941/15536986/2cef32d8-2274-11e6-8a9b-8e5e9cea84f8.png)
I accidentally clicked the vat with my portable tank. And it filled up the left tank. 

An easy way to solve this is a button to allow switching tanks like IC2 does.

**Comment by HenryLoenwind** [comment]
That's what those "empty tank" buttons are for.

**Comment by tterrag1098** [comment]
I think we can all agree that wasting 8 buckets of rocket fuel is not a trivial issue. The issue here is that there is no way to choose what tank a right click goes into.

**Comment by mindforger** [comment]
EnderIO features this nifty Orange and Blue In and Outputs, you could replace the "kill" button with a color switcher :) so when you click the button, the vat changes the in and output tank and visualizes it with the button color

**Comment by HenryLoenwind** [comment]
As one tank is an input and one tank is the output, the logic is quite clear. I see no difference here to e.g. throwing your lone Ender Pearl into the SAG Mill instead of the Alloy Smelter.

But if we want to add a solution, a button to drain the input tank into the output tank would be enough. The output tank can be pulled from. It could even replace the left "dump" button, as that functionality would then be possible by "drain"+"dump output".

**Comment by thomas15v** [comment]
@HenryLoenwind that would work :smile:. 8B may not be much. But I wasn't really happy when I clicked the clear tank button.

**Comment by BlueAgent** [comment]
Something I really liked about the IC2 solid/fluid canning machine was the button that swapped the input and output tank contents. Would that feature be applicable for The Vat as well?
