### ISSUE TITLE
[Suggestion] EU <> RF power converter

### ISSUE THREAD

**Issue by c0rn3j** [SleepyTrousers/EnderIO#3423]
Since the only EU<>RF converter that seems to be available in the newer versions is Immersive Engineering which is currently only 1.8.9 beta, would you please consider adding a power converter?

~~#### What happens:~~
~~Energy Conduits do not connect with IC2 machines~~
~~#### What you expected to happen:~~
~~Ender Conduits connect with IC2 machines and provide power to them~~
~~#### Steps to reproduce:~~
~~1. Place conduits next to IC2 machines~~
~~http://i.imgur.com/L1o4fdL.png~~
~~#### Affected Versions (Do *not* use "latest"):~~
~~- EnderIO: EnderIO-1.9.4-3.0.0.43_alpha~~
~~- EnderCore: EnderCore-1.9.4-0.4.0.26-alpha~~
~~- Minecraft: 1.9.4~~
~~- Forge: 12.17.0.1968~~

**Comment by TheOldOne822** [comment]
The 2 mods use different, incompatible, power systems Ender IO uses the "Redstone Flux" power system (also used by thermal expansion and buildcraft as of version 6.1.2 I believe) and IC2 uses the the "Energy Units" power system. It is possible to make a "cable" that converts between them based on what the attached machine wants/provides but likely would take a lot of work to implement. For example the Mekanism cables converts to it's own system (Joules) for transport when connected to a generator and to what ever system a machine is coded to request for delivery.

**Comment by c0rn3j** [comment]
I made this because I thought it was possible in the 1.7.10 version, I just now realized that I was using powerconverter mod back then... Welp, my bad.

**Comment by VT-14** [comment]
While it is nice and convenient, the power systems are separate for a reason.  They function on different mechanics.

Mekanism was already brought up.  It has had all sorts of little problems with its power cables.  There are several cases where one of its cables attached to something like a capacitor bank would produce infinite power due to rounding in the conversion.


You can look at this in two ways.  Adding this feature would support IC2 despite its unwillingness to switch to RF; and/or you could view it as disrespecting their decision to keep their current power system and breaking one of the balancing points of the mod.

**Comment by CrazyPants** [comment]
Thanks for the suggestion, but I think that would belong in a seperate mod.
