### ISSUE TITLE
Zombie spawner bugged

### ISSUE THREAD

**Issue by Visstick** [SleepyTrousers/EnderIO#3470]
#### Issue Description:
Latest version of EnderIO in unstable 1.10.0 by FTB

#### What happens:
Lots of minizombies in my spawning room that are not being killed by killer joe. Nor can I kill them by hand. I walk trough them and they do not attack me either. Filled the room with lava and that didnt help.

Next to that is an active zombie spawner that counts to 100% but does not spawn any zombies anymore.

http://imgur.com/6gG43oh

#### What you expected to happen:

Zombies being killed and zombies being spawned (like it did yesterday)

**Comment by HenryLoenwind** [comment]
You are probably using an old spawner that was created before we added support for the 1.10 changes to zombies.

**Comment by Visstick** [comment]
That could be.

After a serverreboot the issue disapreared. However it reapeared a while later.

I will ask my admin to spawn in a new spawner to replace the one placed in 1.9.4. From there on we will monitor if the issue happens again.

**Comment by HenryLoenwind** [comment]
Update: I added some code to the spawning to handle all kinds of mobs riding other mobs. So the next build would fix your spawner, too. That'd leave you with a working rare "all kinds of zombies" spawner. ;)

Just a little background: The "frozen" zombies you get are actually riding chickens. However, those chickens don't exist in-world because they are created at 0/0/0. The old code left spawning zombies completely to vanilla code, which worked for those chickens but gives random zombies. The new code handles zombies manually, so husks and zombies are different spawners. But your spawner has no type information, so only half of the new code applies. Which mostly works, but for those chicken-riding zombies it fails. The new new code can do both.

**Comment by Visstick** [comment]
Thanks for the quick response,

Like I said I will replace it with a new one. cause when those chicken do
spawn the spawner stops working until a server reset. I need that zombie
meat to make power so I can not afford the system to stop.

Thanks anyway

Gl with your mod
