### ISSUE TITLE
[Suggestion] EU Conduits

### ISSUE THREAD

**Issue by RealKC** [SleepyTrousers/EnderIO#3472]
Note: I've searched and discovered that suggestion simmilar to this have been made in the past, however, they weren't exactly how I think you could implement this.

The conduits would behave like normal ones, but when you would open their interface, they would have a slot for Transformer Upgrades, and depending on the number of transformer upgrades, it would have a different voltage level, as follows:

1.None-Low Voltage
2.1Transformer Upgrades-Medium Voltage
3.2 Transformer Upgrades-High Voltage
4.3 Transformer Upgrades-Extreme Voltage
5.4 Transformer Upgrades- Insane Voltage

The recipe for it should require 6 conduit binder and 3 copper cables giving 8 EU conduits.

While adding this to the normal conduits would be harder, if it'll be decided to be done this way, each tier should increase its voltage, making the Ender Energy Conduit HV. In order to be able to put the transformer upgrades, you would need to put an Electric Circuit in it and you would get a new slot for the transformer upgrades.

**Comment by HenryLoenwind** [comment]
added to the list

**Comment by VT-14** [comment]
In respect to similar suggestions, I'm against power conversions in random mods.  It's often messy, and the IC2 dev has decided to stick with EU for a reason.  Power converters have their place, but not in a clearly RF mods that include cables that can magically convert between RF and EU with no real reason to use EU.

But, EU Conduits?  Yes please.

But I would go with a different implementation.  Like ME conduits and Dense ME Conduits, mirror the original as best as possible.  Ideally, there would be tin, copper, gold, HV (iron), and glass fiber, plus or minus any that I forgot or have been added/removed since I last used IC2.  There are also 'insulated' ones that should be thrown in there as well.  They should have the same power transfer and limits, power loss over distance, and explosion (or lack their of?) when overloaded as the original in IC2 cables.  The GUI should be simple, like the RF Energy Conduits; only one button to decide the connection status.  In/Out and Disabled are obvious ones.  Separate In and Out options would be nice if EU can support it (though I think all IC2 machine sides are 1 way power only, so kind of a useless feature).  If the RF conduits have Redstone Control, then that would also be fair game if EU can support it.

**Comment by EpicSquid** [comment]
Already on the suggestion wall. Please vote for it there. And a conduit api exists so other devs can make it themselves if they want.

**Comment by aaronfranke** [comment]
What suggestion wall? The "Bug Reports and Suggestions" button on http://enderio.com/ just links to the GitHub issues page.

**Comment by mindforger** [comment]
yeah i can remmeber i hinted to seperate those buttons a while ago as it is misleading

**Comment by EpicSquid** [comment]
http://ideas.theideawall.com/EnderIO/Forum/Details/886d8952-7b6b-41b7-b4ab-2904e565aaf0 this one here
