### ISSUE TITLE
Cooking Lycanites raw meat leads to odd results.

### ISSUE THREAD

**Issue by vdrake77** [SleepyTrousers/EnderIO#3547]
Lycanites raw chupacabra meat turns into cooked yale meat in the alloy smelter.  I'm not sure why, but in a regular furnace it turns into the right thing.  Seems like some work, but Concapede becomes Joust, raw Maka becomes Yeti, Ika becomes Cephignis (which is extra weird because raw cephignis meat doesn't exist), Chupacabra becomes yale, and aspid becomes pinky meat.  All of them work fine in regular furnaces.

____
- EnderIO: EnderIO-1.10.2-3.0.1.75_beta
- EnderCore: EnderCore-1.10.2-0.4.1.41-beta
- Minecraft: 1.10.2
- Forge: 2018

**Comment by KendziGE** [comment]
With other raw food, same odd results. 
I.e. Raw Calamari (Pam's Harvestcraft) turns into Firm Tofu (Pam's too). 
Raw chicken turns into Steak

Modpack is FTB Unstable 1.10 Version 4.2.5 with updatet EnderIO and EnderCore
EnderIO: EnderIO-1.10.2-3.0.1.77_beta
EnderCore EnderCore-1.10.2-0.4.1.43-beta
Minecraft 1.10.2
Forge: 2027

**Comment by HenryLoenwind** [comment]
That's caused by the Ore Dictionary. Mods register their items as being the same as some other items. This is used by Ender IO's machine to always give you the same kind of output, e.g. the same kind of copper ingot, no matter what kind of copper ore you smelt.

However, it has become commonplace to register items in as many categories as possible. So those categories are used more like tags. So if mods 'tag' all their edible items as "food", it's no wonder they all smelt into the same item.

We're most probably remove that feature in the near future. So you will again get all kinds of different coppers from smelting copper ore...
