### ISSUE TITLE
Capacitor Banks resetting output and input to 0 RF/t

### ISSUE THREAD

**Issue by Codeick** [SleepyTrousers/EnderIO#3577]
#### Issue Description:
Capacitor banks in EnderIO are resetting their input and output values to 0 RF/t.

#### What happens:
When I start up the world in singleplayer the capacitor banks (setup in multiblock) reset the input and output to 0 RF/t.

#### What you expected to happen:
For the input and output to stay at the same values as set by the user, not to reset to 0 RF/t.

#### Steps to reproduce:

1. In singleplayer, setup several capacitor banks together to form a capacitor bank structure.
2. Supply power to them and change the input and/or output values.
3. Restart the **client** and load up the world.
4. Check the input and output.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.81_beta
- EnderCore: 1.10.2-0.4.1.46-beta
- Minecraft: 1.10.2
- Forge: 12.18.1.2044

#### Your most recent log file where the issue was present: 

http://pastebin.com/kmBzMHF9

NOTE: It happens when I restart the **client**, NOT the world.

**Comment by Rakinare** [comment]
I can not confirm this. Tried it on exactly the same versions multiple times, working just fine.  Are you playing a modpack? If yes, pleas tell me which and the version, so I can try under those circumstances.

**Comment by HenryLoenwind** [comment]
I actually had this happen to me a couple of times in multiplayer.

**Comment by lakotajames** [comment]
Happened to players on my server as well.  We think it might be when the server goes down, but not sure.

**Comment by markozar** [comment]
Hi, I also can confirm this. It happens each time I start the client. I have a client server configuration running on my computer. The server runs on forge-1.10.2-12.18.1.2092-universal.jar, while the client is 1.10.2.
You can find the latest logs here:
[fml-server-latest](algo.synology.me/~Marko/mc/logs/fml-server-latest.log)
[latest](algo.synology.me/~Marko/mc/logs/latest.log)
You will see a kind of mess in the log because this is a test world where I added and removed mods,

This is a screenshot of the setup:
[batteries setup](algo.synology.me/~Marko/mc/logs/2016-10-27_19.27.55.png)
and this the list of the mods I have installed on server:
[batteries setup](algo.synology.me/~Marko/mc/logs/mods.txt)

I also think that input and output values resetted while playing, without restarting client, I just checked the battery after a while and it was again to 0 rf/t. But I can not confirm this 100%. If I get some evidence of this I will post here.

**Comment by MatthiasMann** [comment]
@markozar which was fixed in build 121 on Oct 11.

**Comment by markozar** [comment]
Wonderful, thank you!
I did not find it on curseforge but searching on google I found it on http://maven.tterrag.com/com/enderio/EnderIO. I hope it's correct.

**Comment by MatthiasMann** [comment]
I use http://ci.tterrag.com/job/EnderIO-1.10/ and http://ci.tterrag.com/job/EnderCore-1.10/

**Comment by markozar** [comment]
Nice to know, thank you!
