### ISSUE TITLE
refined storage interaction

### ISSUE THREAD

**Issue by popps73x** [SleepyTrousers/EnderIO#3750]
refined storage interaction (v1.1.1) using Ender io (v3.0.1.116 beta) with ender core (v0.4.1.56 beta) in Curse Pack "Hades Effect" (v1.8.5) Sag Mill will not pull Flint or Ore from a Refined Storage "Interface" it will also not place product into the interface. Is there something in how inventories are handled that is causing them not to interact as I would expect? or is refined storage the cause of the problem and i need to report to them? thanks to refined storage interaction

**Comment by bookerthegeek** [comment]
The problem goes in the post, not the title.

I'm ignoring it til you follow the guidelines

**Comment by popps73x** [comment]
refined storage interaction (v1.1.1) using Ender io (v3.0.1.116 beta) with ender core (v0.4.1.56 beta) in Curse Pack "Hades Effect" (v1.8.5) Sag Mill will not pull Flint or Ore from a Refined Storage "Interface" it will also not place product into the interface. Is there something in how inventories are handled that is causing them not to interact as I would expect? or is refined storage the cause of the problem and i need to report to them? thanks

**Comment by popps73x** [comment]
sorry.  new to this and not technically proficient.   interface is placed adjacent to the sag mill.  interface is set to keep flint and iron ore in its inventory and is connected to a valid storage system with those items available.  in AE2 1.7.10 this system would auto process ore by push/pulling from the interface.  sag mill does not seem to interact with the interface in refined storage.

**Comment by MatthiasMann** [comment]
That's why there was the template for you to fill out - to provide the required information in a structured and easy to read way - instead of having it as an unstructured block of text.

**Comment by HenryLoenwind** [comment]
sorry, misclick

**Comment by Gepett0** [comment]
Quoting the RS wiki:

> The Interface acts as an interface between the world and the system.
> 
> It acts as an inventory so pipes from other mods or hoppers can put items in the system (if there is a space).
> 
> There is also an option for exporting items from the system.
> 
> To clear an exported item configuration use shift and click on the item to clear. Use the left and right mouse buttons to increment or decrement the amount that has to be exported.

> Insertion	Any side, besides bottom side
> Extraction	Only bottom side

Did you try any other machines with the interface? Did you try to pump items with conduits into the SM? Did you use the bottomside of inteface to extract? And top for insertion?

**Comment by VT-14** [comment]
Issue recreated.  From my testing, Refined Storage Interfaces appear to be sided and items in the 'on hand' slots (bottom row, which is filled depending on what is filtered in the middle row) are only pulled out of the bottom.  Items can be inserted on any side, and items in the input to RS system slots (top row) can be removed from any side if the item pulling is faster than the RS system (possibly the cause of @Gepett0 having it work from any side).  I was unable to find any obvious way to rotate the Interface to make the active side any other than the bottom.

I tested with the Ender IO SAG Mill, Ender IO Item Conduits, IndustrialCraft2 Macerator with pulling upgrade, and Blood Magic's Item Routing system.  All of them only pulled out of the bottom of the Interface.

I believe this is an issue with Refined Storage.  Check with them.  This may be intentional, in which case I would suggest a new texture for the Interface that implies the block is sided.
Minecraft 1.10.2
Forge 12.18.1.2095
Refined Storage 1.1.2
Most recent available on Curse for all other mods mentioned.

Temporary Solution: Place RS Interfaces on top of the SAG Mill and other machines.

**Comment by HenryLoenwind** [comment]
thx VT-14 for investigating

**Comment by popps73x** [comment]
Thank you for your help.  yes it appears that it is an issue with Refined storage and the "sided" ness of its blocks.  sorry for wasting your time.  :(
