### ISSUE TITLE
weather obelisk - cant pump out / reset

### ISSUE THREAD

**Issue by battlebovine** [SleepyTrousers/EnderIO#3781]
#### Issue Description:

Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".
#### What happens:

I can pump fluids into the obelisk but once input I'm not finding a way to change the fluid type or pump it out. I also cannot get a new rocket to load and launch into the air after the first one is done. 
#### What you expected to happen:

change fluids. Either void the existing fluid or pump it out or just over write it with a new one and launch a new rocket to change the weather. 
#### Steps to reproduce:
1. place obelisk and fluid tank down and pump fluids in using a conduit
2. launch rocket with the button 
3. ? 
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- EnderIO: 1.10.2-3.0.1.120_beta
- EnderCore: 1.10.2-04.1.56-beta
- Minecraft: 1.10.2
- Forge: 8.0.99.99
#### Your most recent log file where the issue was present:

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
1. That the fluid cannot be pumped out is intentional. You need to either build multiple obelisks or carefully control the amount of fluid you put in.
2. You cannot change the weather to the current weather, only another weather. The launch button will only be available if the fluid is for another weather than the current one,
