### ISSUE TITLE
Incompatibility with LightningCraft

### ISSUE THREAD

**Issue by DatrixTHLK** [SleepyTrousers/EnderIO#3786]
#### Issue Description:
When both EnderIO and Lightningcraft are present game crashes
Reference Issue from [LC issues page](https://minecraft.curseforge.com/projects/lightningcraft/issues/22)

#### What happens:
Crash happens when both LightningCraft and EnderIO are present but take one out and it doesn't crash

#### What you expected to happen:
Everything to cooperate and no crash to occur.

#### Steps to reproduce:

1. Take out Lightning Craft  and leave EnderIO game works 
2. Take out EnderIO and Coremod and leave LightningCraft the game works
3. Keep both EnderIO, CoreMod and LightningCraft and the game crashes
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.120_beta
- EnderCore: 0.4.1.55-beta  
- LightningCraft2: 2.6.0
- Minecraft: 1.10.2
- Forge: 12.18.2.2114

#### Your most recent log file where the issue was present: 

Crash Log: https://gist.github.com/DatrixTHLK/7eaf4fc0ed4dc3f6c809019d0c32a6a2

**Comment by HenryLoenwind** [comment]
lightningcraft uses a method that will always crash, because @LexManos thinks that including methods with Forge that behave that way is a good way to show how much more intelligent than all modders he is.

A switch() on an Enum will crash if the Enum contains a different amount of elements at runtime than at compile time. That's what's happening here. Don't use net.minecraft.item.Item.ToolMaterial.getRepairItem() or net.minecraft.item.Item.ToolMaterial.getRepairItemStack().

**Comment by sblectric** [comment]
Good to know, thanks.

**Comment by DatrixTHLK** [comment]
I see. I doubt it would be intelligence if that were the case, or it could just be a simple mistake. Either way Lex will fix the issue. Thanks for the information though.

**Comment by DatrixTHLK** [comment]
I see.
