### ISSUE TITLE
Requests List+Ender IO Modules

### ISSUE THREAD

**Issue by BurovB** [SleepyTrousers/EnderIO#3833]
I think that Ender IO is interesting enough, it would be more globally. It's be better if you add this:
1.Void Miner(Can mine resources(ores) from nothing. It will be a multiblock structure, and it must have bedrock block under a. If you took colored glass into machine it would working like linse which increase drop chance of something ores. 5000 RF/t. It will have an "Ender Upgrade" which wolud be work like a filter(you put into it ores) and when you took it into machine it will be more slower and "eat" 20000 RF/t, but it will mine only that ore which are in filter)/
2.Breeding mobs(Machines which will be feed animals, and move it by the filter(expamle. I will move from that area to another area only childs ))
3.Chemistry
       +
4.Fusion reactor          [Something like in Mekanism]
       +
5.Augmentations of ore
I offer to "cut" Ender IO on modules:
1.Core(Craft components and basic machines for production this componets)
2.Agriculture(Powered Spawner, Farming Station, mob breeding, Killer Joe)
3.Ender Tech(All magitech, Dimensional Transceiver,...)
4.Chemistry
5.Generators
6.Mining(Void Miner, augmentations of ore)
7.Another

**Comment by VT-14** [comment]
These are just my opinions.  I am not involved in Ender IO Development. I have no comments on 1 or 2 beyond that they seem to be inspired by MineFactory Reloaded.

3) Chemistry ... for what purpose?

4) Fusion Reactor - Reactors are only really used/needed because of RF power creep, which Ender IO has refused to contribute to (For instance, they have repeatedly refused to increase the power transfer limits on their conduits/dimensional transceiver).  I doubt we will ever see a 200+ RF/t generator in Ender IO.  Also, don't copy Mekanism just for the heck of it (I'm including request 3 when I say that).

5) Again, for what purpose?  I think the SAG Mill giving ~3x ore processing (Dark Steel Balls) and extra byproducts (like the occasional Gold from Copper) is powerful enough to not need a boost.

'Cut' into modules: I never understood why some mods do that.  I can understand core mods, like EnderCore; "add-ons" that are extremely different, like RFTools Control; or potentially OP modules that aren't required in the main mod, like RFTools Dimensions...

...But I never understood cutting mods into little pieces like Mekanism's separate tool download, or all of CoFH's "Thermal" modules.  That just seems like needlessly increasing the mods downloaded counter and causing confusion.

**Comment by predakanga** [comment]
I'd like to add that although there are some good reasons for splitting mods into separate modules, EnderIO deals with that by being very configurable - basically anything you don't want can be disabled through the config.

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion. It has been added to our list or possible enhancement.

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by HenryLoenwind** [comment]
Half of that stuff already is on our TODO list, the other half is either "that's not Ender IO" or "no way we could find the time to do that".

**Comment by Agares** [comment]
Is the TODO list publicly available somewhere?

**Comment by HenryLoenwind** [comment]
partially. there are the labels "Suggestion" and "Improvement" and there are the "Projects". But many of the things we want to do long-term we just talked about, e.g. "we want to do animal handling some day" and "splitting eio into modules would be nice but probably more work than it's worth".

**Comment by BurovB** [comment]
@HenryLoenwind 
KO, Google)

**Comment by BurovB** [comment]
I think that Inventory Pannel would be better than AE if you upgrade it.

**Comment by BurovB** [comment]
Phew...

**Comment by BurovB** [comment]
Did you read changed coments?
