### ISSUE TITLE
Conduits and Facades become invisible

### ISSUE THREAD

**Issue by Xiaminou** [SleepyTrousers/EnderIO#3910]
#### Issue Description:
Until now I thought it was only me since no one else had reported the issue but in today's episode of DW20's he got the same bug I have randomly occurring for a while.

https://youtu.be/Z6n0hLDZiCk?t=4m33s

#### What happens:
Conduits and Facades randomly become invisible when holding the YETA Wrench.

#### Steps to reproduce:
Don't know.

____
#### Affected Versions (Do *not* use "latest"):

- Server
- EnderIO: 3.0.1.139_beta 
- EnderCore: 0.4.1.61-beta
- Minecraft: 1.10.2
- Forge: 2185
- Mods: [list.txt](https://github.com/SleepyTrousers/EnderIO/files/649230/list.txt)

**Comment by HenryLoenwind** [comment]
Already been reported by Dire, and I still have problems recreating it when I need to.

**Comment by Xiaminou** [comment]
Alright, I couldn't find an issue so I wasn't sure if he had reported it or not.

**Comment by HenryLoenwind** [comment]
yeah, not a problem. Some people report directly to avoid being that visible to their fans, so it's not bad to have this issue to track it.

**Comment by RobertLSnead** [comment]
It seems to happen every time my server reboots/refreshes!

![before_server_reboot](https://cloud.githubusercontent.com/assets/5366796/21278955/d9286640-c3ab-11e6-9897-145161294f19.png)

![render_glitch](https://cloud.githubusercontent.com/assets/5366796/21278940/ca079262-c3ab-11e6-830b-fb62ca5f7705.png)

**Comment by RobertLSnead** [comment]
It appears to happen on all connections to an inventory when in insert mode, export mode seems to not be affected.

**Comment by Xiaminou** [comment]
It can happen on any conduit, no matter if it's connected, import, export. I can't find a pattern.

**Comment by HenryLoenwind** [comment]
So, if other blocks are also effected, it may not actually be something in Ender IO doing that...

**Comment by Xiaminou** [comment]
I've never seen it affect other blocks, I do get other visual glitches but they seem to be unrelated.

**Comment by RobertLSnead** [comment]
What ever the glitch it seems to happen every time on server reboot.
Place cables down and reboot/refresh server and you will see the glitch every time!

**Comment by HenryLoenwind** [comment]
duplicate to #3787

**Comment by Xiaminou** [comment]
Went around my base after building EnderIO from github, couldn't find any bugged conduits. Looks like it's fixed.

**Comment by HenryLoenwind** [comment]
I really hope so. I could never reproduce it but for my very first try when Dire contacted me on IRC.

**Comment by RobertLSnead** [comment]
Not sure why this was closed?  I am getting the following render glitch with ver. 3.0.1.142 beta.

![render_glitch2](https://cloud.githubusercontent.com/assets/5366796/21295392/21c5595e-c522-11e6-9cfb-a526dec5cf8f.png)

**Comment by Xiaminou** [comment]
This might be a different bug, if you look on the screenshots and videos we posted the facades outlines don't even render. Yours do.

**Comment by HenryLoenwind** [comment]
It may be the same thing. I added this "cubes in cubes" display for empty conduit bundles, which would render as empty before.

So what you see here are conduit blocks that have no conduits in them, according to their renderer.

Can you reproduce this? If so, I'd make an Ender IO build with some debugging code for you to test some things.

**Comment by HenryLoenwind** [comment]
Everyone who has this problem: Please use build 143 from http://ci.tterrag.com/job/EnderIO-1.10/143/ (or later, I'll leave this in until the issue is finally resolved) and right-click the effected conduits with a stick. You'll find debugging info in the client logfile ("You clicked on TileConduitBundle..."), please post that here together with a screenshot and please describe which output line is which conduit.

**Comment by RobertLSnead** [comment]
Here is some data!  See Attached!

[Glitch Data for EnderIO.txt](https://github.com/SleepyTrousers/EnderIO/files/659764/Glitch.Data.for.EnderIO.txt)

**Comment by RobertLSnead** [comment]
Hope the information helps solve the issue!

**Comment by HenryLoenwind** [comment]
Yes, @RobertLSnead, that information is indeed helpful. It turns out the rendering isn't to blame here...the conduit block is indeed empty (on the client).

For you, changing the Yeta Wrench display mode doesn't change anything, does it?

**Comment by RobertLSnead** [comment]
I was not able to get any render differences from the glitched out conduits, different wrench modes work fine on the normal conduits.  I was also not able to find any error messages on client nor server.  I have attached the log files for your viewing pleasure. 

[fml-client-latest.log.txt](https://github.com/SleepyTrousers/EnderIO/files/662117/fml-client-latest.log.txt)
[fml-server-latest.log.txt](https://github.com/SleepyTrousers/EnderIO/files/662118/fml-server-latest.log.txt)

**Comment by RobertLSnead** [comment]
I'm not sure what happened but, I was messing with the wrench modes and dragging it across from glitch to normal and now it keeps crashing when I get on my server.  Crash log attached.

[crash-2016-12-19_16.14.07-client.txt](https://github.com/SleepyTrousers/EnderIO/files/662152/crash-2016-12-19_16.14.07-client.txt)

**Comment by HenryLoenwind** [comment]
see #3931 for that crash

**Comment by RobertLSnead** [comment]
Well, I was able to find another way around that bug lol.  I did notice that I can shift click with the wrench and the conduit does drop as normal, this again is only temporarily as usual.

**Comment by RobertLSnead** [comment]
Is there a way to force update the conduit? It's strange how it fixes it self when connecting onto the same chain of conduits or if breaking the chain of conduits.  Not sure how the conduits determine the chain it is a part of?  Just a thought.

**Comment by HenryLoenwind** [comment]
Your problem is that the conduit's data isn't sent from the server to the client. As this is the job of the base game, and it usually works just fine, I have no idea where to even start looking for a cause.

I haven't forgotten you, it's just that I have no clue what to do. For now try to be consoled by the fact that this is only a display error, those conduits should still work fine.

**Comment by RobertLSnead** [comment]
I am not sure entirely how the code is setup or works but, I do have an interesting idea how to solve the problem.  It tends to fix itself with a chain update (break or add to existing chain).  Is it possible to check at a given tick to check the chain it is connected to and see if one of the conduits has that state and then force a chain update to force render?  Just an idea.

**Comment by HenryLoenwind** [comment]
I could add code to the conduits that runs client-side and detects that the conduit list of the is empty, then sends a network packet to the server to trigger a forced update. But, that'd just be a workaround for one type of block. There is a problem getting server data to the client and I see no reason this should effect conduits only. It's just that you don't see it with the other blocks because they render the same was all the time.

**Comment by thommy101** [comment]
I've got the same problem. It's limited to one chunk only, which contains my Mekanism ore processing.
Just updated to the latest version to get some of the debug info. The empty conduits are displayed in The One Probe as Conduit Connector.
I'm also reporting it to the Mekanism repository, because the pipes of it are also gone.

Clientlog, serverlog, modlist
https://gist.github.com/thommy101/995fa39fbf44eb8d46d8a3eb141087cc

Screenshots
http://imgur.com/a/RsDsT
