### ISSUE TITLE
EnderIO items can only be charged via EnderIO

### ISSUE THREAD

**Issue by Nuinethir** [SleepyTrousers/EnderIO#3992]
#### Issue Description:

EnderIO-1.10.2-3.1.156 - EnderIO items will not charge through other RF power mods (specifically Mekanism).

#### What happens:

EnderIO tools/items can only be charged via EnderIO mechanisms (inserted directly into a Capacitor Bank or walking near a Wireless Charger). EIO can charge other mod items/blocks. Mekanism can charge other mod items/blocks EXCEPT EIO items.

Something about EIO items not being accepted by Mekanism (where Mekanism accepts other mods' items/blocks).

#### What you expected to happen:

With earlier versions (1.7.10), EnderIO items (such as the Electromagnet) would charge in any mod's charging slots (such as Mekanism Energy Cubes). This is no longer possible.

#### Steps to reproduce:

1. Create Electromagnet.
2. Try to place in Mekanism Energy Cube (not accepted). Charging Pad has same effect.
3. Electromagnet will charge via Capacitor Bank or Wireless Charger.
4. Other Mekanism items/blocks can be charged by EnderIO (as in Step 3).
5. Mekanism has no problem charging other mods' items/blocks.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.1.161
- EnderCore: EnderCore-1.10.2-0.4.1.64-beta
- Minecraft: 1.10.2
- Forge: 1.10.2-forge1.10.2-12.18.3.2202

#### Your most recent log file where the issue was present: 

http://pastebin.com/reFejuqq
(nothing really relevant)

**Comment by MatthiasMann** [comment]
EnderIO only supports Forge Energy and Tesla for items. As you posted the client log I can't see if you have the Tesla API in your mod pack or not.

**Comment by HenryLoenwind** [comment]
You got it backwards. Open this with mek.

**Comment by Nuinethir** [comment]
@MatthiasMann As you mentioned Tesla (which was not in my pack), I downloaded the latest for 1.10.2 (Tesla-1.10.2-1.2.1.49) and still had no success. Also, sorry about the log file. The fml-client-latest also won't paste into pastebin (over 512KB). Here is my mod list...

http://pastebin.com/wZrYQXAx

@HenryLoenwind I will try that.

**Comment by Nuinethir** [comment]
I just removed Tesla. It was preventing Mekanism universal cables from charging EnderIO blocks (including the Wireless Charger, which ironically will charge all of my tools/items). What exactly is Telsa supposed to be supporting here?

**Comment by VT-14** [comment]
I'm not a mod developer, but from my understanding: Tesla is a power API meant to replace the old and possibly no longer updated RF API.

Unfortunately, it's part of a "3 competing standards" problem.  A lot of mods are still sticking with the old, original RF API; Forge made its own version called Forge Energy which arguably has the best claim since it's Forge, but some don't like the implementation; lastly, Tesla is a stand alone mod version that has some features people like that came out around the same time.

At the moment, Mekanism has incorrect implementation of the Tesla API.  Aiden never actually finished properly porting Mekanism before he got busy with school, so Mekanism is in a poor state at the moment.  If you stay on the Mekanism Github, someone will probably point you to one of the unofficial forks of it where someone tried to fix the more problematic bugs (like downloading an outdated MCMultipart).

**Comment by SargeRyong** [comment]
I can confirm that neither the Actually Additions Energizer, nor the Immersive Engineering Charging Bench can charge any item from EnderIO, even though they should be able to.  Additionally, AA Batteries won't refill EIO items.  

The only mod charger aside from capacitor banks that seems to work afaik is RFTools Powercells.

**Comment by MatthiasMann** [comment]
@SargeRyong as already pointed out - Actual Additions charger will work when you include the Tesla API in your pack.

**Comment by Nuinethir** [comment]
@MatthiasMann You say that, but as I mentioned above, adding the Tesla API only made things worse (only made mods more incompatible with Ender IO). I also had the same problem with Immersive Engineering that @SargeRyong had.

While you mentioned that Ender IO only supports Tesla and Forge Energy, that is simply untrue as I have all Ender IO machinery powered via Mekanism cabling. My solution is to just use Mekanism's power grid (since it is compatible with everything) with Ender IO Wireless Chargers attached to charge items in my inventory (including Mekanism tools and energy cubes).

**Comment by VT-14** [comment]
So, I did some testing with Ender IO, Actually Additions, and Immersive Engineering.  I did not test with Mekanism due to its numerous problems in this subject already being well documented on its GitHub (aidancbrady/Mekanism#4116, aidancbrady/Mekanism#3911).  It's worth noting that all "charging blocks" were sucessfully charged by using Ender IO's Ender Energy Conduits and a Creative Capacitor Bank.

Tested Charging Blocks:
-Ender IO Capacitor Banks
-Actually Additions Energizer
-Immersive Engineering Charging Station
-RFTools Powercell
-Applied Energetics 2 Charger

Tested RF Accepting Items:
-Ender IO Staff of Travelling
-Actually Additions (AA) Single Battery
-Immersive Engineering (IE) Railgun
-RFTools Charged Porter
-Refined Storage (RS) Wireless Grid
-Applied Energistics 2 (AE2) Wireless Terminal


Without Tesla Installed:
-Ender IO - Charged everything
-Actually Additions - Did not charge Ender IO nor Applied Energetics 2 charge items.
-Immersive Engineering - Same as Actually Additions
-RFTools - Charged Everything
-Applied Energistics 2 - Only charged the AE2 item

With Tesla Installed:
-Ender IO - Charged everything (again)
-Actually Additions - charged everything (exactly as @MatthiasMann said)
-Immersive Engineering - Did not charge Ender IO nor AE2 items (no change)
-RFTools - Charged Everything (again)
-Applied Energetics 2 - Only charged the AE2 item (no change)


Ender IO items were charged by only Ender IO and RFTools, with AA only adding support through Tesla.  AE2 is a bit of a weird one; but I believe it will turn several different power APIs into AE's energy, but not the other way.  Otherwise, AA, IE, RFTools, and RS items were charged in anything.

That looks like Ender IO is doing something weird with its items receiving RF, or Immersive Engineering (and AA without Tesla) are doing weird things that many other mods work with anyway.

Mod list (from manual debug crash).  Using Minecraft 1.10.2
Forge{12.18.3.2221} [Minecraft Forge]
-actuallyadditions{1.10.2-r98} [Actually Additions]
-appliedenergistics2{rv4-alpha-11} [Applied Energistics 2]
-endercore{1.10.2-0.4.1.65-beta} [EnderCore]
-JEI{3.14.4.404} [Just Enough Items]
-EnderIO{1.10.2-3.1.161} [Ender IO]
-immersiveengineering{0.10-55} [Immersive Engineering]
-mcmultipart{1.3.0} [MCMultiPart]
-notenoughwands{1.5.3} [Not Enough Wands] - I forgot to change config to use RF
-refinedstorage{1.2.20} [Refined Storage]
-rftools{5.82} [RFTools]
-tesla{1.2.1.50} [TESLA]

**Comment by MatthiasMann** [comment]
@VT-14 EnderIO *items* no longer accept RF - only Forge Energy or Tesla.
But EnderIO conduits and machines still support RF when the RF API is available (it is no longer bundled).

@Nuinethir I have several MC 1.10.2 instances with EnderIO, AA and Tesla API - and they work just fine together - I even use the AA battery to charge my EnderIO items in my inventory.

If you have other mods which do not handle Tesla API correctly then that is *not* EnderIO's fault - either rise that issue with these mods or remove them.

**Comment by tterrag1098** [comment]
If I had to guess, mekanism is handling Tesla improperly, resulting in it both trying to use Tesla for EIO items (because we support it) but failing because tesla is not installed. No idea why problems crop up if you DO have Tesla, but again, this sounds entirely on Mekanism's side.

**Comment by HenryLoenwind** [comment]
Mekanism is suffering from a massive case of "half-way done". Don't expect other mods to fix Mek's bugs for it...

**Comment by VT-14** [comment]
@MatthiasMann I used "RF" because that's how most mods displays the power regardless of what APIs it is using.  This competing standards thing can get confusing. :/

That nicely explains Actually Additions needing Telsa for items but working with everything else... but Immersive Engineering supposedly supports Forge Energy now.  Tonight, I'll try testing it against mods that don't use the RF API at all and open an issue with them if needed.
