### ISSUE TITLE
Editing Light Level

### ISSUE THREAD

**Issue by LokyLive** [SleepyTrousers/EnderIO#4005]
Hey i'm looking for a way to edit light level (of Enlightened Fused Quartz/Glass,Powered Light and Light)  i've alreadry try few things so i decide to try to remove their recipe and i'm still unsuccess ...

Could you help me please to edit this ?

**Comment by HenryLoenwind** [comment]
There is no configuration for the amount of light those blocks give off. Why would you want to reduce it?

For recipes, those are in the alloy smelter recipe config file (for quartz) and in the machine recipe file (for the lights). There are instructions on how to disable recipes in those files.

**Comment by LokyLive** [comment]
I work on a modpack and i 'm doing an overall of modded basics goal so my first goal is to create a progression in lightning device . I already remove/rework vanilla light source and some modded .

**Comment by HenryLoenwind** [comment]
Ok, then I recommend you change the recipes for the "light" (LL15) to be more expensive, the "powered light" (LL15 + AOE) way more expensive or disabled or use a huge amount of power. The "wireless light" may either stay or go, it's recipe already is non-trivial.

The other light sources, Enlightened Quartz/Glass and Painted Glowstone, already take one Glowstone block for each and have the same LL. So by limiting the player's access to Glowstone, they should already be regulated. Nearly the same goes for Glowgas, but there you get a flowing liquid which you can stretch out over quite an area if you know what you're doing.

Fluid conduits give off the same light level as the liquid inside. But because you can fill less conduits than you could have liquid blocks if you let the liquid flow, I think that's ok. (Also, it can be disabled, "fluidConduitDynamicLighting".)

I'm a bit concerned about Conduit Facades. Those mimic the light level of the block they are painted with. So with a single glowing block and a good supply of sand, gravel and clay, you could light up the whole world.

**Comment by LokyLive** [comment]
Actually i can't change any light level on EnderIO that's why i'm asking ,p
 I've already edit lava glowstone ect... light level so i think you can paint as many glowstone as you want it will not give you light ^^

For conduit lighting i've already ask for this config that's why this config appear in last version

**Comment by LokyLive** [comment]
bump ?
