### ISSUE TITLE
Soulbound deleting items

### ISSUE THREAD

**Issue by resinate** [SleepyTrousers/EnderIO#4104]
#### What happens:
when you die with soul bound items are deleted on death

#### What you expected to happen:
keep the items?

#### Steps to reproduce:

1.apply soul bound
2.die or use /kill
3.cry in tears??
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1-10.2-3.1.179

#### Your most recent log file where the issue was present: 

no logs/errors are given

**Comment by HenryLoenwind** [comment]
For the last 3 years there has not been a single instance of a soulbound malfunction that wasn't caused by other mods messing with the death processing improperly. So either reproduce the problem with only Foreg+Endercore+EnderIO and provide a full log, or provide a full list of mods that are installed so I can refer you to those that are likely candidates.
