### ISSUE TITLE
Dimensional Transceiver Bug (?)

### ISSUE THREAD

**Issue by Buddy-xR** [SleepyTrousers/EnderIO#4105]
#### Issue Description:
The Dimensional Transceiver is able to input more energy than it is supposed to.

#### What happens:
I created a creative world to test the dimensional transceiver, and I placed down two creative capacitors each with a dimensional transceiver connected to it, which are both sending energy.  I then have a bunch of vibrant capacitor banks set up with a single dimensional transceiver connected to it which is receiving power from the two other dimensional transceivers.  The two dimensional transceivers that are sending energy are sending a max of 40,960 rf/t like they are supposed to, but the single dimensional transceiver is inputting more than 40,960 rf/t into the capacitor bank.

#### What you expected to happen:
The Dimensional Transceiver to max out at 40,960 rf/t

#### Steps to reproduce:

1. Send more than 40,960 rf/t over multiple dimensional transceivers on the same "network"
2. Connect a single dimensional transceiver to a capcaitor bank that can input more than 40,960 rf/t, and receive the energy being sent from the other dimensional transceivers.
3. Look at the input values of the capacitor bank, which should be over the 40,960 limit that is supposed to be applied
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.179
- EnderCore: 1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 12.18.3.2254

#### Your most recent log file where the issue was present: 

Not available

**Comment by aelfwyne** [comment]
Math on the capacitor banks doesn't add up either, which doesn't help in figuring out what's going on. I basically just gave up on trying to figure out where power was going and have just built the world's largest "extreme reactor" fueled by an environmentaltech void miner getting tons of yellorite. No need to track power usage any more... Basically had to go overkill because the enderIO stuff has some funky math going on with the RF.

**Comment by mindforger** [comment]
can you post pictures of the setup ?
