### ISSUE TITLE
Painted glowstone blocks placed next to another block that’s one block above it, it becomes lighter than it should be

### ISSUE THREAD

**Issue by PapiDimmi** [SleepyTrousers/EnderIO#4123]
If I place a painted glowstone block in the middle of the floor somewhere, it looks exactly like the block it’s painted as, but if I place it on the floor next to a wall or a block of any kind, its texture becomes noticeably lighter.

![2017-03-30_21 13 49](https://cloud.githubusercontent.com/assets/25916106/24521894/06a462fc-158e-11e7-9ca0-9887336d5902.png)

**Comment by PapiDimmi** [comment]
@HenryLoenwind Why did you close all the issues that I’ve created?

**Comment by bookerthegeek** [comment]
@PapiDimmi they are closed for multiple reasons.

Just from looking at this one it is because ypu failed to include any information of versions. 

Also, though I doubt many people will come atraight out and tell you this due to common courtesy, you are very anoying when you are told something you do not agree with. You become argumentative and demeaning to people. You should learn to have common curtesy when interacting with people online.

**Comment by HenryLoenwind** [comment]
as bookerthegeek said.

Also, for this one: Other blocks get darker in the corner because Minecraft simulates there being less light. However, why should a block that gives off light get less light from its surroundings in the corner? It doesn't matter how much it gets from its surrounding, it will always be fully bright from its own luminosity.

If its bother you that much, you can always switch off Smooth Lighting in the video options.

**Comment by PapiDimmi** [comment]
Sorry for not including the necessary information.
