### ISSUE TITLE
Farming Station planting wrong seeds

### ISSUE THREAD

**Issue by Chelebi** [SleepyTrousers/EnderIO#4165]
#### Issue Description:
The Ender IO Farming Station is deploing the wrong seeds if u use Barley seeds from the Natura Mod.
instead of Barley it's planting Cotton seeds from the Natura Mod but it's consuming the Barley seeds.

#### What happens:
Farming Station using Barley seeds but planting Cotton

#### What you expected to happen:
Farming Station using Barley seeds to plant Barley

#### Steps to reproduce:

1.Setup Farming Station
2.Put in Barley seeds
3.Watch
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.180
- EnderCore: 1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 8.0.99.99
-Minecraft Forge: 12.18.3.2254

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by MatthiasMann** [comment]
Just to clarify some things - you only put barley seed in the farming station and no other type of seed (that's what I'm going to assume).

As I currently do not have a pack with Natura can you check the item ID of these seed (by using F3-H to show debug tooltips).
I assume that both seeds share the same item ID with a different meta data.

**Comment by HenryLoenwind** [comment]
Can anyone confirm the data with Natura? I have:

* grown barley block: "Natura:N Crops" meta=3
* grown cotton block: "Natura:N Crops" meta=8
* freshly planted cotton block: "Natura:N Crops" meta=4
* barley seed item: "Natura:barley.seed" meta=0
* cotton seed item: "Natura:barley.seed" meta=1

**Comment by Chelebi** [comment]
current Pack im using is FTB Beyond 1.5.3
Natura Version is: 1.10.2-4.1.0.34
Barley seeds ID: (#7711/0) 7711
Cotton seed ID: (#7711/1) 7711:1
tile.natura.barley_crop.name (#7709/0)
tile.natura.cotton_crop.name (#7710/0)
Block ID shown with AgriCraft Debugger Tool (#4634)
Planted Barley block ID: natura:barley_crop Meta: 0
Planted Cotton block ID: natura:cotton_crop Meta: 0

**Comment by PaleoCrafter** [comment]
I can confirm the naming Chelebi pointed out for the blocks, the seeds have the ID "natura:overworld_seeds".

Not sure if this is best put here or if it warrants an issue of its own, but besides the barley/cotton thing, Natura berry bushes also aren't handled by the Farming Station correctly. because they were renamed since 1.7.10. The new naming scheme is "natura:(overworld|nether)_berrybush_[berryname]" as far as I can tell, each berry being a separate block/item.

**Comment by HenryLoenwind** [comment]
2 things:

* Natura changed its mod-id, so our Natura code is not engaged at all. So all Natura seeds and plants are handled by the vanilla code using whatever vanilla interfaces those items/blocks implement. So that both seeds generate the same kind of plant is a bug in Natura and should be reported there.
* New Farming Station code for Natura is in progress.

**Comment by HenryLoenwind** [comment]
Ok, I'm through with the new Natura integration. However, I cannot recommend Natura at all at the moment---too many bugs there.

**Comment by PaleoCrafter** [comment]
Thanks a lot for the quick change! IMO, this issue can be considered closed.

As a sidenote, I'm only using Natura berries since they are a great source of food when combined with the HarvestCraft juicer :D
