### ISSUE TITLE
Killer Joe is exceptionally rough with TiC blades.

### ISSUE THREAD

**Issue by Fokson** [SleepyTrousers/EnderIO#4170]
**What happens / What you expected to happen / Steps to reproduce:**
When giving Killer Joe a sword from TiC (such as the Longsword or the Cleaver) he will consume 4 durability per mob hit.  Additionally, he doesn't seem to respect when a tool has Mending Moss, as it doesn't repair until I retrieve it from him despite having a full pool of exp.  I would attribute this part more to Tinker's coding rather than yours, however.  I would assume that each swing should only be taking one durability.

To reproduce, simply create a TiC blade and give it to Joe.
____
**Affected Versions:**

- EnderIO: 3.1.180
- EnderCore: 0.4.1.65-beta
- TiC: 2.6.3 [ A version that I have "tinkered" with a bit myself, but still holds true for an unmodified version ]
- Minecraft: 1.10.2
- Forge: 12.18.3.2221

**Log:**
http://puu.sh/vp4AB/8a08f31c1c.txt

**Comment by HenryLoenwind** [comment]
We are only calling net.minecraft.entity.player.EntityPlayerMP.attackTargetEntityWithCurrentItem(FakePlayer) with the weapon equipped, not doing anything else to it. So the extra durability most likely is on TiC's side. 

see https://github.com/SleepyTrousers/EnderIO/blob/1.10/src/main/java/crazypants/enderio/machine/killera/TileKillerJoe.java#L267

The moss not working is caused by Forge not firing events for fake players, so TiC has no way of knowing about a fake player holding anything. For the wireless charger we fake it by having the Killer Joe polling for Wireless Chargers., but that's not really feasible to add for each and every mod's special effects...
