### ISSUE TITLE
Killer joe doesn't accept weapons from Draconic Evolution

### ISSUE THREAD

**Issue by SkippyMitch** [SleepyTrousers/EnderIO#4183]
#### Issue Description:
Draconic Evolution weapons are no longer accepted by the Killer Joe? 

#### What happens:
Can't give Killer Joe any draconic evolution weapons

#### What you expected to happen:
I would like for this to be possible, at least in the config.

#### Steps to reproduce:

1. Using Draconic-Evolution - 1.10.2 - 2.0.10.199
and EnderIO - 1.10.2 - 3.1.184
...

____
#### Affected Versions :

- EnderIO: 3.1.184
- EnderCore: 0.4.1.65-beta
- Minecraft: 1.10.2
- Forge: 2281

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.

**Comment by SkippyMitch** [comment]
Honestly just wanted to know if it was intentionally disallowed. not to make a suggestion. I respect your judgment.

**Comment by HenryLoenwind** [comment]
oh, it was a subtle question. Sorry, got lost on me as non-native speaker.

If it ever worked before, then it was because those weapons extended (in a Java `extends` sense) the vanilla sword and stopped doing it. There's a difference between something that extends a sword (axe, shovel, shears, hoe, ...) and a generic item that has code to give it the same behavior. If something *is* a kind of sword, it will work in the Killer Joe because our code knows what to do with swords. If it is a kind of sapling that has code that deal 40 points of damage and set its target on fire, our code knows nothing about it and we have to write new code to deal with that item.

I can do that, but I prefer to have as few pieces of code that depend on other mods not changing their behavior. Those things are a headache to keep up to date. That is one of the reasons I introduced that suggestion tracker---it will show relative demand for things, not just that things are suggested all the time because they are obvious.
