### ISSUE TITLE
Please implement the "Patreon" plugin. 

### ISSUE THREAD

**Issue by ogradyjd** [SleepyTrousers/EnderIO#4232]
There seem to be a lot of clients (users, modpack creators) that have outputs missing termination (money they want to pay you).   And I quote:

> Stop nagging us, or start paying us to quit our day-jobs and do this full-time.

I suggest some kind of interface that is called on a schedule, say once a month: 

```
public interface DeveloperSupport extends Patreon {
    @Override
    Pizza feedMe(Money benjamins);
    default void moralSupport(Accolades lotsalove) {
        /* Changed argument type to Accolades.  Clients still keep
         * trying to call this with Aggrevation.  I mean, they both
         * begin with "A",  but..
         */
    }
}
```

Seriously, you've given us years of fun and a conduit system that's become the de-facto standard for transferring things in the most compact way possible.  I'd chip in a dollar a month, and I'd say so would a lot of other of us gamers that appreciate all the hard work this takes, especially with the recently accelerated update schedule and the steep number of breaking changes you now have to deal with.

You've given us something.  Now it's time to let us give you something back.

**Comment by amiralixxx** [comment]
گیتهاب

**Comment by tterrag1098** [comment]
It is my feelings, which I believe are shared by @CrazyPants, that we would rather any money directed at us go instead to a charity. We do what we do for the fun of it, and don't expect any monetary compensation.

That said, neither I nor him are currently doing much work on EIO, so it is entirely up to @HenryLoenwind what to do, there are no restrictions on EIO that would prevent him from creating a Patreon or something of the sort, and I certainly would have no problem with him doing so.

**Comment by HenryLoenwind** [comment]
I think I need to clarify my statement: I do have a good-paying job and do not hurt for money. However, having that job also means it takes a good chunk of my time doing it. Now *if* I could live from modding and quit my job, then I could invest that time into Ender IO. But, the chances of that happening, and being a long-term viable thing, are next to nil (unless some crazy billionaire decides he likes my work that much).

Please understand that that comment wasn't a request for funding, but a request for people to stop nagging me because I (can only) do this in my limited free time.
