### ISSUE TITLE
Conflict with Draconic Evolution

### ISSUE THREAD

**Issue by llloyd4** [SleepyTrousers/EnderIO#4273]
#### Issue Description:

Have a Draconic Evolution Capacitor, in "Charge Held Items" or "Charge Armor & Held Items" mode and use JEI to get a Creative Capacitor Bank. 
Posted this to DE as well, but, as this can go either way I am also sharing with you. 
https://github.com/brandon3055/Draconic-Evolution/issues/803

#### What happens:

Game CTDs

#### What you expected to happen:

Nothing

#### Steps to reproduce:

1. Posses a charged Draconic Evolution Capacitor
2. Set the Draconic Evolution Capacitor to "Charge Held Items" or "Charge Armor & Held Items" mode
3. Use JEI to create a Creative Capacitor Bank
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.183
- EnderCore: 1.10.2-0.4.1.66-beta
- Minecraft: 1.7.10
- Forge: 1.10.2-12.18.3.2316
- Draconic Evolution: 1.10.2-2.1.0.232

#### Your most recent log file where the issue was present: 

https://pastebin.com/pU9m2Btf

**Comment by HenryLoenwind** [comment]
I had a look at the code, the reason for the crash lies in Brandon Core: It uses the return value of getCapability() without checking it for null.

Note: The energy capability for the creative CapBank has been disabled because some mods could not cope with its unlimited energy.

**Comment by llloyd4** [comment]
Ok, cool, posted this on their Github 2 days ago with no response yet. But Brandon is most likely uber busy so I won't stress this too hard, a friend pointed me to NTB Explorer and I deleted the capacitor bank out of my inventory and got my world accessible again.

**Comment by brandon3055** [comment]
@HenryLoenwind Actually this entirely on EIO. along with "getCapability" there is a "hasCapability" method. The entire purpose of that method is to check if the item has the capability before trying to access it. If something reports that it has a capability then it MUST provide that capability otherwise the hasCapability method is completely pointless. 
When they disabled the energy capability on the capacitor they forgot to return false in hasCapability. This is why its crashing.
