### ISSUE TITLE
"Losing" Item Filters

### ISSUE THREAD

**Issue by psxlover** [SleepyTrousers/EnderIO#4305]
#### Issue Description:
First let me note that I'm on Minecraft 1.7.10, so please excuse me and close this if it has been fixed in a newer version of EnderIO.

When you remove an inventory that is on an item conduit with an item filter in it, the item filter stays in the conduit but you lose access to it. The only way to retrieve it is to place another inventory were the first one was, or remove the pipe.

I first encountered this when I tried to move my setup by one block. I had an item conduit end up on a hopper with a filter permitting only charcoal. At some point I decided to move the hopper one block higher, so I broke it, placed an item conduit above the one that had the filter and placed the hopper above. The filter was still in the original conduit but there was no indication that it existed, and even when I realized where it was there was no way to access the conduit and get the filter other than breaking it.

____
#### Affected Versions:

- EnderIO: 2.3.0.429
- EnderCore: 0.2.0.39
- Minecraft: 1.7.10

**Comment by SteelShot** [comment]
I do not think this is a bug, but rather the way conduits just work, it would be nice if the conduit would just stay as if connected until the filter is not removed. Now to 1.7.10, i am 100% that the devs consider this version **EOL** and maybe only critical bugs will be fixed now days or even completely stop the development. The only way for now until something gets fixed/implemented etc. is to download the repo yourself and modify the code on your own or get some help from someone that is willing to tinker around, this is what i have done at least with couple of mods.

I have tried tweaking enderio before, but it is a quite complex mode and there is a lot of stuff happening specially around the conduits and for now i am playing on 1.7.10 with what there is available :)

**Comment by mindforger** [comment]
i too noticed that behaviour several times before and i simple removed and erplaced the pipe then ... i think it's a quality of life issue not really a bug ... could use some love :)

**Comment by mindforger** [comment]
sure but you brought it up, it is a valid point .. nothing critical but it definately would be a QoL improvement in the end ... the filter could simply snap out when the connection gets removed , this would be pretty understandable but would have 2 following issues then

first situation would be if you replace a machine for example, it would be connected unfiltered until you install a new filter, could be pretty ugly when you work on an highly active system
second situation is the chunkunloading ... imagine a machine on either and the conduit on the otehr side of a chunk and the machine gets unloaded... i don't know how conduits handle this, but if the filter pops out simply because the conduit sees no inventory anymore this would raise compaints about conduits acting up and spitting filters out for supposedly no reason

**Comment by psxlover** [comment]
At the very least, when attaching another item conduit on the side that had the item filter it should get removed.

**Comment by mindforger** [comment]
oh yes i totally agree on that onme :D

**Comment by HenryLoenwind** [comment]
Thank you for your suggestion, but we manage suggestions on http://ideas.theideawall.com/EnderIO

This ticket will be closed because we want the list of open tickets to reflect known issues.
