### ISSUE TITLE
Weather Obelisk automation

### ISSUE THREAD

**Issue by InjuredWolf** [SleepyTrousers/EnderIO#4330]
Any chance of a way to automate the activation of the weather obelisk?

**Comment by xenxero1** [comment]
I'd imagine something like a daylight sensor, maybe an inverter/NOT Gate and comparator setup would work. Only during the day though.  Otherwise plenty of other mods have something to detect weather. Like OpenComputers.

**Comment by Fokson** [comment]
I'd like to second this.  The weather obelisk's refusal to cooperate with the rest of the mod's otherwise seamless automation capabilities seems rather half-baked.  It has an option for redstone control in its GUI that does absolutely nothing.
I'd like to see the ability to fire a weather rocket with a redstone pulse, so I can drown my server in an eternal storm (without having to click the stupid little check mark every few minutes)! >=)

**Comment by tterrag1098** [comment]
Actually, it was originally intended for the weather obelisk to respond to redstone. So I will file this under "missing feature".

**Comment by HenryLoenwind** [comment]
If this is not working report it as bug please.
