### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by GhostShot3** [SleepyTrousers/EnderIO#4341]
Compatibility with bc2
I can not put item conduits in the bc2 quarry would be better if it had compatability with the mod.

**Comment by Aiidoneus** [comment]
I cannot really see this being a thing because of how the bc2 quarry works. (assuming Buildcraft 2)
The way that the bc2 quarry works is that it pushes the mined items to an adjacent inventory as the quarry itself does not have a internal inventory. This is why this doesn't work with conduits as the conduits do not really have an inventory. The simple solution would be to just put a chest down next to the quarry and extract from the chest instead of from the quarry. 
I am not sure what type of compatibility you are looking for with this.

**Comment by GhostShot3** [comment]
I fixed ,can close if want

**Comment by mindforger** [comment]
you can close it yourself, right beside the comment button

**Comment by GhostShot3** [comment]
wow!
