### ISSUE TITLE
EnderIO thinks the RF API is lower than 1.4.0 while it's actually 1.7.0

### ISSUE THREAD

**Issue by Jeppeskovsgaard** [SleepyTrousers/EnderIO#4346]
#### What happens:
I have made my own modpack based on FTB Beyond. 60% of the mods are the same. When I try to launch the game it crashes on launch 90% of the time.

The error log crashes because Ender IO apparently doesn't work with the current RF API from CoFHCore. The error log outputs the following:

An unsupportted RF API is installed (1.7.0 .. )
Ender IO needs at least 1.4.0 and will NOT work with older versions.

This error message obviously makes no sense. The RF API is 1.7.0, but Ender IO thinks it's lower than 1.4.0?

Weird thing is, that 10% of the time, the launch of the game is succesful.

The game has **never** crashed while playing. Only at launch.

#### What you expected to happen:
A succesful game launch.

#### Steps to reproduce:

1. Install this modpack in the Twitch client with forge 12.18.3.2511: https://drive.google.com/open?id=0B7jk0SKCFY9yN3d6djNpbjhZRmc
2. Launch the game
3. Crash on launch
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.183
- EnderCore: 1.10.2-0.4.1.66
- Minecraft: 1.10.2
- Forge: 12.18.3.2511

#### Your most recent log file where the issue was present: 

https://pastebin.com/8uaNTkLd

**Comment by MatthiasMann** [comment]
EnderIo only checks for 2 specific versions of the RF API:
https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/tool/EnderIOCrashCallable.java

everything else is marked as "unsupported" - it doesn't even try to compare the version strings.

As your versions also says "1.7.0" but without the "R1.0.0" or "R1.0.1" suffix it's hard to say if your version is newer or older as the 2 versions known to EnderIO.

But in any case the crash in your log is not related to EnderIO. Try starting the game without the resource packs.

**Comment by Jeppeskovsgaard** [comment]
Thanks for a quick an useful response. Unfortunately the same thing happens without the resource packs.

Since all mods are up to date, that means many of them are in beta, and I guess there are a lot of bugs or inconsistencies.

I have duplicated the beyond pack, added a few mods of my own and now use the same forge version. It works perfectly now, so I guess that is my solution for now.

**Comment by HenryLoenwind** [comment]
That link goes to the 1.7-version, here's the one for the 1.10-version: https://github.com/SleepyTrousers/EnderIO/blob/1.10/src/main/java/crazypants/enderio/diagnostics/EnderIOCrashCallable.java#L46-L80

You get that message because we had problems with people using an RF-API for Minecraft 1.7.x on Minecraft 1.10. Now that the RF-API has progressed to version 1.7, it is a false alarm.

To find which mod crashes the game, use a binary search. That is:

1. Remove half of the mods
2. If it still crashes, the bad mod must be in the half that stayed, if not, it must be in the half that was removed
3. Put the removed mods back
4. Remove half of those mods you identified in step 2 as "must contain the bad one"
5. Go to step 2
