### ISSUE TITLE
1.12.2 Energy Conduits not working after Server restart

### ISSUE THREAD

**Issue by chris42** [SleepyTrousers/EnderIO#4607]
#### Issue Description:
After a server restart, enhanced power conduits seem to stop sending power to certain machines. Occurred with RFTools Elevator and Thermal Expansion Compactor. The conduits are still connected, but no power is delivered. removing them and rebuilding them starts power delivery again. 

#### What happens:
No power is being delivered although connector is connected and properly configured. Machine runs on internal power until empty

#### What you expected to happen:
Regular power delivery

#### Steps to reproduce:
This error does not seem to pop up on each server start, but randomly. Hence multiple starts are needed.
1. Connect RFTools Elevator or Thermal Expansion Compactor to enhanced power conduits and send power.
2. Restart server
3. Use machine and check power storage in machine

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.22
- EnderCore: 1.12.2-0.5.22
- Minecraft: 1.12.2
- Forge: 14.23.3.2666

#### Your most recent log file where the issue was present: 
Log of last server start, after which the Compacter had no power. However cannot tell if it occurred exactly in this start.
https://pastebin.com/kWk4dnH9

**Comment by EpicSquid** [comment]
This is not something I can make happen under the same conditions

**Comment by chris42** [comment]
So anything I can do? Produce logs, enable debugging or anything? If you explain me what you would be looking for, I could try to get it.

**Comment by tterrag1098** [comment]
A minimal reproduction case would be most helpful. A world save where the issue is repeatable, with a minimal set of mods where the problem still occurs. This way we can test it ourselves and get more info.

**Comment by lAimBotl** [comment]
This is similar to something I am experiencing on my server, I used a gpm to check rf levels and I got this: 
![2018-05-13_14 37 07](https://user-images.githubusercontent.com/10777735/39970544-409c6706-56bb-11e8-9c87-64328e6615f5.png)

I did modify the config though (not over the limits though)

**Comment by EpicSquid** [comment]
@IAmBotl your issue is unrelated and to do with your config choices.

**Comment by FlixCoder** [comment]
I just came across, because I have the same issue in Singleplayer:
For me this was the case:
I have some generators and tier 1 energy cables. I connected a Pulverizer, SAG Mill, Alloy Smelters and Induction Smelters (not important). But the energy conduits passed the Pulverizer at two sides. I deactivated one side, so I can connect everything to power capacitors, not directly to generators. But anyway, after restarting, the Pulverizer did not get any engery until I broke the conduit and placed it again. Later I changed the cables and the Pulverizer is connect with only one side now. It works perfectly now.

**Comment by EpicSquid** [comment]
@FlixCoder not relevant to the 1.12 release, also appears to be a different issue.

**Comment by MajorTuvok** [comment]
I'm experiencing a similiar issue **only on a multiplayer server**. Though I have tested it with an capacitor bank and the powered spawner (Tier 2 capacitor). Apperently enhanced energy conduits emit correctly to other capacitor banks (or for that matter to mekanisms energy cubes) but when sending power to some special blocks, like the powered spawner it simply doesn't send it. Additionally, restarting the server doesn't work for me...

**Comment by Sanofus** [comment]
I had the same issue in singleplayer. After I left and joined the game again a machine of Mekanism ran out of energy although it was connected with energy conduits. But it was only one machine and always the same so I thought it was a bug with that machine. I could rebuilt that and test this for you if you want?

**Comment by PlasticPhoenix** [comment]
What are you using for power generation? I've also noticed the problem, but only when I generate power with Thermal Expansion dynamos. I CANNOT get energy out of them. I've tried Energy Conduit (EIO), Transfer Nodes (XU2), Laser Relays (AA) no luck. These all work fine feeding out of a basic capacitor bank though, so I don't think the problem is in the EIO cables. I am feeding my machines out of a piddly culinary generator and it works perfect with all forms of energy transfer. If you're in SP, cheat in/make another power generator and see if it works. I'm going to go poke around the COFH stuff and see if they broke something accidentally.

**Comment by Sanofus** [comment]
I had only to replace the cable. The energy came from a Quantum Entangle Porter. But there were several machines connected and only one was affected. I assume you have problems to get the energy out? 
My problem was to get the energy in.

**Comment by PlasticPhoenix** [comment]
Yep, I couldn't get power out. But, it still happened even with other mods' power cables, so I don't think my issue was EIO related. I've not tried messing with QEP's or anything like that. I'm all old-fashioned direwire style, but I mainly use EIO because they seem to work the best for my setups.
