### ISSUE TITLE
[1.12.2] Client Crash due to checking permissions client side

### ISSUE THREAD

**Issue by Morpheus1101** [SleepyTrousers/EnderIO#4618]
Crash report @ https://gist.github.com/Morpheus1101/a6ff580a02aea3af796d04d7ba953318

Forge v *.3.2678
EIO v 5.0.24
E.Core v0.5.22

Full Complete Details of information can be found @ https://github.com/MinecraftModDevelopment/New-MMD-Public-Pack/issues/57

**Comment by EpicSquid** [comment]
Last time I looked into this issue it was a problem on ftbutils end

**Comment by HenryLoenwind** [comment]
Forge's DefaultPermissionHandler has special code to handle the "client in multiplayer" case, which leads me to believe that the PermissionAPI was designed to run in parallel on client and server like all the other world interactions. However, I've sent a question towards Forge to get definitive word on this.

**Comment by HenryLoenwind** [comment]
Update: Lex says calling it on the client is valid.

**Comment by Morpheus1101** [comment]
ok then that leaves FTBU then since it crashes purposefully with that occuring. thanks for the updated info

**Comment by LatvianModder** [comment]
Permission mods dont even exist on clients, I never designed the PermissionAPI to be used on clients. I  1.13 the api redesign won't allow anything on client, so I'd recommend getting used to not checking perms on client. I dont even know how you imagine perms working on client since they are not (and won't be) synced
