### ISSUE TITLE
Soul Binder Strangeness w/ Refined Storage

### ISSUE THREAD

**Issue by trittimo** [SleepyTrousers/EnderIO#4628]
This is a crosspost of an issue I filed at [Refined Storage](https://github.com/raoulvdberge/refinedstorage/issues/1786). I don't know which side is causing this.

#### Issue description:
Soul binders have some sort of strange behavior going on in Refined Storage.

https://youtu.be/OPQMqXUimDs

#### What happens:
If you have a soul binder that you have performed at least one operation with, you will not be able to extract it from a network using a grid (of any kind). This is a really strange bug. So far I have not found any other EnderIO items that are acting like this.

If you have an exporter and another soul binder, you can get the soul binder into a chest... but there seems to be a ghost item that stays in the drive. Since this is a such a strange bug, I have attached a video (see above).

Another thing: if you get two soul binders (both having been used), they seem to condense into one item. This is one of the weirder bugs I've seen.

#### What you expected to happen:
There is no weirdness. They behave like other items and can be extracted through a grid. They don't leave ghost items behind.

#### Steps to reproduce:
1. Get a soul binder from EnderIO.
2. Charge it up and perform at least one operation (this does not work without this step!)
3. Put the soul binder into a drive and attempt to do things with it in a crafting grid.
4. Voila.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.3.2689 (most recent as of 5/13/18)
- Refined Storage: 1.5.33 (most recent as of 5/13/18)
- EnderIO: 5.0.24 (most recent as of 5/13/18)
- EnderCore: 0.5.22 (most recent as of 5/13/18)

I also have Refined Storage Addons version 0.3 (most recent as of 5/13/18)

Does this issue occur on a server? No.

#### If a (crash)log is relevant for this issue, link it here:
Log is not relevant as far as I can tell, but [here's a link.](https://gist.githubusercontent.com/trittimo/1b8a611440bb428e4b44991d9b474aca/raw/da458bf644bdf1ed90c8f80dfad91a6d7b43a3e7/latest.log)

**Comment by HenryLoenwind** [comment]
From our side this is just a normal item with some nbt.

**Comment by wamc2017** [comment]
Hmm, I think this has something todo with the experience nbt tag. I reproduced this bug in a testworld and looked at the nbt data of the soul binder:

![experience](https://user-images.githubusercontent.com/33242447/39972247-65cbd926-570b-11e8-94e9-97f3128c4d04.png)

Before crafting anything the experience value is 0, after crafting the value is NaN, the tag itself seems to be encoded as float, so I guess Refined Storage expects some kind of number in there and not NaN, because when I change it back to 0 with a nbt editor, everything's fine.

Don't know on which side that's easier to fix, but maybe EnderIO could return 0 instead of NaN....

**Comment by Aksenty** [comment]
> So far I have not found any other EnderIO items that are acting like this.

I have this bug with Experience Obelisk.
Minecraft: 1.12.2; Forge: 14.23.3.2655; Refined Storage: 1.5.33; EnderIO: 5.0.24; EnderCore: 0.5.22.
