### ISSUE TITLE
[Question] Will inventory Panels be ported in the future

### ISSUE THREAD

**Issue by acanady** [SleepyTrousers/EnderIO#4648]
So i asked a question previously and it was closed before I could get more information. I'll restate here.
Yes, i know inventory panels are not currently ported. They're not in the latest release (5.0.24) so yeah I get that. My question is, **is their currently work being done on porting inventory panels, if not will there be in the future, or has the development team decided to remove Inventory Panels all together.** A great many changes have been made to EnderIO so it's unsure what the development looks like going forward.

**Comment by alxpettit** [comment]
I honestly think this is a poor way of handling user questions, as it doesn't let other people see answers already given. I recommend adding a "I have questions about..." option on your [issue thingy](http://loenwind.info/eio_issue.html), and just have it direct to a separate issue tracker or forum or something. That way you can build up a searchable repository of answered questions.

**Comment by acanady** [comment]
Well that's not really what alxpettit was talking about. It is a poor way of handling user questions. Discord isn't really a repository,  it's a chat service. So you'll have repeated questions a lot. If answered questions were done as a github or something similar then users could see answered and unanswered questions. Other mods have done a similar thing. True there will still be duplicate questions, but it will be one step toward not having too many and having a place where people can easily see duplicate questions. Or you know, keep doing what you're doing eithers fine.

**Comment by EpicSquid** [comment]
Discord has just as many ways of dealing with this problem as github does. We have chosen to do it this way because more people communicate on our discord so it just makes sense. I have no issue with answering questions, heck on our discord you can even see progress updates for inventory panel, so it just makes githubess practical overall for us if nothing else.

**Comment by alxpettit** [comment]
Hmm. Apparently Discord _does_ have a searchable history. I'm impressed! I can see how it works for this use case. If it was open source, I might consider using it on a regular basis!

**Comment by EpicSquid** [comment]
We also pin messages that are common and we have a bot that can be queried for answers.

**Comment by alxpettit** [comment]
I looked at your README.MD for this repository, and couldn't find anything about where to post questions to and search for answered questions. Maybe you should add a link to your Discord and make sure people know to direct them there?

I personally spent like 20 minutes wandering around random EnderIO stuff online because I didn't know Discord had search history and such -- so it might be useful to point people there and be like "no really, try it" on the README.MD.
