### ISSUE TITLE
Server crash when placing oc adapter next to oc cable in facade

### ISSUE THREAD

**Issue by Nathan1852** [SleepyTrousers/EnderIO#4672]
#### Issue Description:
Minecraft crashes when placing an OpenComputers adapter next to the newly readded OpenComputers conduit in a facade. 

#### What happens:
Minecraft crashes with a NullPointerException

#### What you expected to happen:
Minecraft doesn't crash

#### Steps to reproduce:

1. place oc conduit
2. place oc adapter next to it
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.25
- EnderCore: 1.12.2-0.5.30
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

#### Your most recent log file where the issue was present: 

[crash-2018-05-31_16.56.10-server.txt](https://github.com/SleepyTrousers/EnderIO/files/2058741/crash-2018-05-31_16.56.10-server.txt)

**Comment by ttamnedlog** [comment]
Just to add some my own data and crash report, in case it's useful, since it's still happening in slightly newer versions of these mods:

#### Issue Description: Immediate crash upon placing OC conduits next to OpenCoputers cables. If single player, the client immediately crashes to desktop. If on server, the server immediately crashes but the client just gets kicked to menu.


#### What happens: See above?



#### What you expected to happen: OC conduits and OpenComputers cables to work hand in hand



#### Steps to reproduce:

1. Place a line of OC conduit
2. Break one of the OC conduit in the middle of the line
3. Place an OpenComputers cable where the OC conduit was, between the remaining OC conduits
...
I didn't explore if any less specific steps would produce the crash, but those are the exact steps I did when I discovered the crash, and those are the exact steps I tried twice more to reproduce the crash. 

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.26
- EnderCore: 0.5.31
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

#### Your most recent log file where the issue was present: 

https://paste.ee/p/v1QQF
