### ISSUE TITLE
Early game machines

### ISSUE THREAD

**Issue by madkingdiamond** [SleepyTrousers/EnderIO#4723]
#### Issue Description:
.The early game Machines are bugged. 

#### What happens:
I try to open the UI and it doesn't open. Instead it bugs my inventory and i have to relog.

#### What you expected to happen:
The UI to open.

#### Steps to reproduce:

1. https://i.gyazo.com/thumb/1200/3937a93ca956289b6a3e98a5662fb2af-png.jpg <-- Picture of player UI after trying to access machines.
2. https://i.gyazo.com/thumb/1200/34db2ee3109e73b8197d94447a0c9df5-png.jpg<--- Picture of machines that dont open.
3. Everybody on the server has this issue
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.26.jar
- EnderCore: 1.12.2-0.5.31.jar
- Minecraft: 1.12.2
- Forge: 14.23.4.2707

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by tyler489** [comment]
Mods list please.

**Comment by HenryLoenwind** [comment]
Scrambled inventories are created when server and client open different GUIs.

**Comment by tyler489** [comment]
In ATM 3 Latest Patch

**Comment by madkingdiamond** [comment]
I am playing on a whitelisted server. The server isnt mine. I'm just trying to figure out why its doing that so i can play. I'm assuming id need the logfile from the server owner?
Or does it generate one on my side?

**Comment by HenryLoenwind** [comment]
see also https://github.com/AllTheMods/ATM-3/issues/635

**Comment by tobywf** [comment]
#### Issue Description:

I get this issue in Direwolf20 modpack. I know the issue template says to report it to the modpack, but given it's exactly the same issue with exactly the same versions and I have a log file, maybe it's appropriate to amend this issue? (If not, I'll repost on their issue tracker.)

#### What happens:

0. I crafted a tank, and filled it with lava (not sure if related, but it's the first thing I did with EnderIO)
1.  I crafted a Simple SAG Mill/Simple Alloy Smelter/Simple Stirling Generator
2. I placed them in world
3. I right clicked the Simple Stirling Generator
4. UI does not open
5. Inventory is scrambled, common items added to armour slots, sometimes items appear duped or disappear (until relog)
6. Also happens with other machines (Simple SAG Mill/Simple Alloy Smelter)

#### What you expected to happen:

UI opens and inventory is untouched.

#### Steps to reproduce:

See "What happens". Issue is not resolved by restarting server.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: mods/EnderIO-1.12.2-5.0.26.jar
- EnderCore: mods/EnderCore-1.12.2-0.5.31.jar
- Minecraft: 1.12.2
- Forge: 14.23.4.2709

(Confirmed client and server versions match)

#### Your most recent log file where the issue was present: 

The log file starts when I start progression towards EnderIO machines. Previously I crafted a tank, so let me know if you need previous logs, and I'll see if I still have them:

https://gist.github.com/tobywf/0dd1f6c85db9865b25412e52117ad36d

The log contains a NullPointerException, but having said that, restarting the server does not fix the issue, and  subsequent relogs have the same behaviour but do not cause the same exception:

https://gist.github.com/tobywf/f8cdc5bdcc99e6228b324daafe0ba113

Thanks!
