### ISSUE TITLE
Client crash on right-click on any Block in JEI

### ISSUE THREAD

**Issue by Bulldog83** [SleepyTrousers/EnderIO#4744]
#### What happens:

Game crashes when I try to righ-click on EnderIO's machines in JEI, to see their recipes. 

#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.29
- EnderCore: 0.5.35
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

#### Your most recent log file where the issue was present: 

https://gist.github.com/Bulldog83/7ec41d98060822c8ac983a0022430ae4

**Comment by HenryLoenwind** [comment]
Try reading the error message:

`Fluid nc.fluid.FluidCoolant@b195b50 (redstone_nak, class nc.fluid.FluidCoolant) from item 1xitem.techreborn.cell@0 returned an unregistered block from getBlock(). This is a major bug in the mod that fluid belongs to.`

**Comment by mindforger** [comment]
nuclear craft

**Comment by Bulldog83** [comment]
Ok, sorry. But before update this error didn't occur. And nor NuclearCraft or TechReborn did update too.

**Comment by HenryLoenwind** [comment]
https://github.com/turbodiesel4598/NuclearCraft/issues/312

**Comment by turbodiesel4598** [comment]
Hey there - sorry about this. The way to fix this should be to head into the NC configs and enable the addition of fluid blocks to the game.

They are disabled by default because I had issues reported related to running out of block IDs, as NC adds hundreds of fluids which can send big packs over the limit.

**Comment by Bulldog83** [comment]
I've set B:register_fluid_blocks=true in NuclearCraft config and this issue has gone. But I've taken new client crash on the same action.
https://gist.github.com/Bulldog83/54de91219d54bd696a5af1906acaa75d
Yes, this again is not an EnderIO issue, but... Why didn't these crashes exist before the update? (With NC I've understood).

**Comment by Bulldog83** [comment]
This crash occurs on right-cliking on any Block in JEI. And problem not only in "broken" blocks from another mods. I think, problem also in "crazypants.enderio.base.paint.PaintUtil".
https://gist.github.com/Bulldog83/f9e1fbd16b9cda11280294378f2e1b27

**Comment by DaNeo61** [comment]
same here no NC Installed 
log says PaintUtil and Tinker_IO Fluid

https://gist.github.com/DaNeo61/85588caa6f3bb58ff8f03ec1aedccbea

**Comment by tyler489** [comment]
Bug in tinker io not registering their fluid as a block. Not an enderio bug

**Comment by 2001zhaozhao** [comment]
I just thought of a temporary fix - maybe the issue can be prevented by using CraftTweaker to remove the offending fluids from JEI. I do not have time to test this right now, might test it later to see if it works.

**Comment by Bulldog83** [comment]
Set B:allowTileEntitiesAsPaintSource=false in EnderIO.cfg eliminates the problem.

**Comment by 2001zhaozhao** [comment]
That fix does not work for me. I can not look at the uses of cobblestone right now without crashing because some Factory Tech fluid doesn't add a block. If I remove Factory Tech I get another mod that doesn't have a fluid block, and so on. It is just bad coding to try to enforce something that many mods currently do not do.

**Comment by HenryLoenwind** [comment]
So throwing a good error message instead of just crashing randomly is bad coding in your eyes?

**Comment by Bulldog83** [comment]
On the one hand, your position in something is good. But on the other hand, when the mod pack has more than two hundred mods, this creates a very big problem.

**Comment by 2001zhaozhao** [comment]
Mods like NuclearCraft intentionally do not register fluids because of block IDs, a very valid concern. I am aware that there is a mod to remove the limit but having too many IDs nevertheless increases network bandwidth substantially.

Just because Forge or something recommends registering unique blocks for fluids does not mean that Ender IO should simply crash the entire game when even one mod doesn't do it. Especially so since there's a good reason not to register a fluid, and that doing so usually does not cause serious consequences.

Oh, and EnderIO doesn't even offer an option to turn off the painting machine nor its JEI compatibility modules.

**Comment by tyler489** [comment]
@2001zhaozhao
https://github.com/turbodiesel4598/NuclearCraft/issues/333

They dont have to register there fluid to a block.... they could set it to null and it would still work without taking more ids...

**Comment by turbodiesel4598** [comment]
Yep, that is my fault - I have fixed it in dev and will add a failsafe.

**Comment by HenryLoenwind** [comment]
As tyler said, there is no reason to make a block and attach it to a fluid if you don't register it. And handing out unregistered objects to other mods is just plain wrong,

**Comment by joshuasuperboy** [comment]
just try to install the latest version of tech reborn and maybe that will fix it

**Comment by Bulldog83** [comment]
One more, with Chisel
https://github.com/Chisel-Team/Chisel/issues/721

**Comment by Sunekaer** [comment]
https://pastebin.com/2zu6zYfi

**Comment by HenryLoenwind** [comment]
Hey, @Sunekaer, you posted a message to this ticket! Just thought I'd tell you, so you know!
