### ISSUE TITLE
Optifine+EnderIO crash

### ISSUE THREAD

**Issue by GuerreroCraft61** [SleepyTrousers/EnderIO#4920]
#### Steps to reproduce:
1.EnderIO+Optifine
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.36
- EnderCore: 0.5.41
- Minecraft: 1.12.2
- Forge: 1.12.2 - 14.23.5.2768
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? Join minecraft

#### Your most recent log file where the issue was present: 
[https://hastebin.com/yobojumeno.sql]

**Comment by VT-14** [comment]
1) Always include the full crash report.  All of the information put in there is important.

2a) The snippet you included very clearly says "(That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.)"

2b) In case it's not clear, Ender IO adds that note if Optifine is installed, regardless of if it's related to the crash or not.  If the only difference between crashing and not crashing is just having Optifine, then the stacktrace near the top may tell you which mod is actually conflicting (there's a pretty good chance it isn't even Ender IO).  Hence, point 1.

3) If this problem actually was caused by Optifine, then make sure your Optifine is up to date, and if it is, then report the issue to Optifine.  Optifine is basically a highly invasive core mod that is closed source; developers from other mods have no idea what it's doing, so the Optifine developers needs to be involved.

**Comment by HenryLoenwind** [comment]
5. It adds this notice to tell you to NOT come pestering us about any issues with Optifine because we can and will not support you with any Optifine-related issues.
