### ISSUE TITLE
Having a recipe bug and no idea how to fix it

### ISSUE THREAD

**Issue by ghost** [SleepyTrousers/EnderIO#4928]
#### Issue Description:

Ok I have a player who reported an issue here, https://github.com/TacticalUniverse/Beyond-The-Void-2/issues/19#issuecomment-433949388 and is saying in screenshot 1 is posted is the wrong recipe but in screenshot 2 is the right one. I don't have any clue how to fix that cause I have no custom recipes set for that and can't figure it out

#### What happens:
Seems like the recipe is broken but not sure

#### What you expected to happen:
An answer to how to fix it

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.37
- EnderCore: 1.12.2-0.5.43
- Minecraft: 1.12.2
- Forge: 1.12.2 forge-14.23.5.2772
- SpongeForge? yes/no no
- Optifine? yes/no no
- Single Player and/or Server? single player and server

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

Dont have one just screenshots posted by the place in the above link

**Comment by LumberWizard** [comment]
Might be a UniDict or JAOPCA issue caused by the alternate cobalt block from chisel.  Can you pastebin or gist your configs for UniDict and JAOPCA?

**Comment by LumberWizard** [comment]
I can confirm in my own heavily modded instance with both UniDict and JAOPCA this issue doesn't happen, it must be a config or script issue. The cobalt block is only in blockCobalt.

**Comment by TacticalUniverse** [comment]
I would not know where to look as I have over 290 mods in my pack @LumberWizard

**Comment by LumberWizard** [comment]
If you want to remove those blocks from that oredict entry using CraftTweaker (it might be possible with our XML recipe format but I don't know much about it) you can add:
```
<ore:oreCobalt>.remove(<tconstruct:metal:0>);
<ore:oreCobalt>.remove(<tconstruct:metal:1>);
```

**Comment by VT-14** [comment]
The easiest/fastest way to find a problem mod if you have absolutely no idea is to remove half your mods.  If the problem persists, you know it's in the remaining half, otherwise it's in the disabled half.

Repeat with that half until you single out the problem mod.  With 290 mods it will take no longer than 9 cycles, and it will probably take far less due to core mods and dependencies.

That said, I would start with Crafttweaker (a custom script error), Tinkers' add-ons, and things like JAOPCA.

While you can certainly can address this issue with either CraftTweaker or Ender IO's custom recipe system, that's treating the symptom, not the disease (unless it's a pack error with CraftTweaker).  Whatever mod does this will not fix it unless they are told about it, and not many mods work with Tinkers's unique ores out of the box (It's actually Ender IO adding the dust forms).

**Comment by LumberWizard** [comment]
In this case it's JAOPCA adding the dust forms actually, but it shouldn't be the one at fault because it doesn't do that in my instance.

**Comment by LumberWizard** [comment]
Oh, just downloaded and checked - this is Ex Nihilo ardite dust.
