### ISSUE TITLE
Dark Armor settings not saved between world loads

### ISSUE THREAD

**Issue by SReject** [SleepyTrousers/EnderIO#4960]
#### Issue Description:
Dark armor on/off states are not saved when reloading the world

#### What happens:
In single player, if you toggle various aspects of your dark armor off such as step assist or jump, exit minecraft and restart those settings are not saved.

#### What you expected to happen:
The armor settings to be saved between loads

#### Steps to reproduce:

1. Create dark armor boots and power them
2. Toggle dark armor 'Step Assist' off
3. Walk around to ensure step assist is off
4. Save and Quit
5. Exit minecraft
6. Restart minecraft
7. Reload world
8. Step assist is on again

This happens with all toggle-able armor settings.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.38
- EnderCore: 1.12.2-0.5.43
- Minecraft: 1.12.2
- Forge: 14.23.5.2775
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Single Player

#### Your most recent log file where the issue was present: 

[log](https://bpaste.net/show/ebd8279193d9)

**Comment by HenryLoenwind** [comment]
Works as designed, but I admit that it's annoying. So I'll tag it to be changed.

**Comment by SkippyMitch** [comment]
*Posting comment here instead of creating a new issue*
I am using another mod for step assist in my pack, so there is **constantly** a message on the screen saying, "Step Assist may be disabled by another mod." until I toggle step assist of the DarkSteel armor (after every world load, which is often for me) I would ask for there at least to be an option to disable this error message.
