### ISSUE TITLE
PI doc area needs to be a little smarter.

### ISSUE THREAD

**Issue by brandon3055** [SleepyTrousers/EnderIO#5102]
#### Issue Description:

The current implementation simply uses all available space to the left of the GUI. It does not take into account the high possibility that there may be buttons from other mods like JEI in that area.

![](https://user-images.githubusercontent.com/19277301/56089816-ccf82380-5e66-11e9-8aa9-24b96a19c102.png)
This issue was brought up over on the [PI issue tracker](https://github.com/brandon3055/ProjectIntelligence/issues/8) 
I recommend something something similar to what the default handler does.
https://github.com/brandon3055/ProjectIntelligence/blob/1b2bc800c709b201dfa0bff12a88376b1b91c615/src/main/java/com/brandon3055/projectintelligence/registry/DefaultHandlerImpl.java

**Comment by HenryLoenwind** [comment]
JEI takes up the complete left side and complete right side of the screen, so we cannot simply move out of the way. We also do not get any feedback from PI on the status of the documentation, we just tell it where it can put it so it doesn't interfere with our GUI. We also tell JEI where it cannot put its stuff because we need the space for our GUI. PI just needs to do the same (`mezz.jei.api.gui.IGlobalGuiHandler.getGuiExtraAreas()`).

@brandon3055

**Comment by brandon3055** [comment]
Funny you should mention that xD
![](https://ss.brandon3055.com/9f764)
I still recommend leaving a little space at the top and bottom because JEI is not the only mod that adds buttons. I have increased the priority on the PI mouse listener so at the very least you should be able to bless the close button no matter what now. As long as no one else uses Priority.HIGHEST on their buttons...
