### ISSUE TITLE
Stoneblock 2

### ISSUE THREAD

**Issue by ThunderStorm0002** [SleepyTrousers/EnderIO#5109]
#### Issue Description:

When i start a world in singleplayer the world crash and in the crash report, there is this "  Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):"

#### What happens:

World crash

#### What you expected to happen:

World opening

#### Steps to reproduce:

1. open modpack
2. open the world
3. world crash
...

____
#### Affected Versions 

- EnderIO: 5.0.43
- EnderCore: 0.5.52
- Minecraft: 1.12.2
- Forge: forge-14.23.5.2808
- SpongeForge? no
- Optifine? yes
- Single Player 

#### Your most recent log file where the issue was present: 

https://paste.dimdev.org/raw/gajaribunu

**Comment by LumberWizard** [comment]
Did you read what you just sent here? "That does NOT mean that Ender IO caused the crash or was involved in it in any way."

**Comment by HenryLoenwind** [comment]
Or this part? "We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker."

Anyway, this has nothing to do with Ender IO. Some mod does naughty things in its block model, like drawing onto the screen instead of generating a model. No way to find out which one with just the crash.
