### ISSUE TITLE
[1.12.2]Rejecting connection SERVER: Ender IO: Failed mod's custom NetworkCheckHandler

### ISSUE THREAD

**Issue by TTVInfernalKontrol** [SleepyTrousers/EnderIO#5177]
#### Issue Description:
[18:18:58] [Netty Client IO #10/INFO] [FML]: Rejecting connection SERVER: Ender IO: Failed mod's custom NetworkCheckHandler FMLMod:enderio{5.0.46}
Ender IO Applied Energistics Conduits: Failed mod's custom NetworkCheckHandler FMLMod:enderioconduitsappliedenergistics{5.0.46}
Ender IO Conduits: Failed mod's custom NetworkCheckHandler FMLMod:enderioconduits{5.0.46}
Ender IO Integration with Forestry: Failed mod's custom NetworkCheckHandler FMLMod:enderiointegrationforestry{5.0.46}
Ender IO Integration with Tinkers' Construct: Failed mod's custom NetworkCheckHandler FMLMod:enderiointegrationticlate{5.0.46}
Ender IO Integration with Tinkers' Construct: Failed mod's custom NetworkCheckHandler FMLMod:enderiointegrationtic{5.0.46}
Ender IO Machines: Failed mod's custom NetworkCheckHandler FMLMod:enderiomachines{5.0.46}
Ender IO Open Computers Conduits: Failed mod's custom NetworkCheckHandler FMLMod:enderioconduitsopencomputers{5.0.46}
Ender IO Powertools: Failed mod's custom NetworkCheckHandler FMLMod:enderiopowertools{5.0.46}
Ender IO Refined Storage Conduits: Failed mod's custom NetworkCheckHandler FMLMod:enderioconduitsrefinedstorage{5.0.46)
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.0.46.
- EnderCore: 1.12.2-0.5.59
- Minecraft: 1.12.2
- Forge:14.23.5.2838
- SpongeForge? no
- Optifine? no
-  Server

#### Your most recent log file where the issue was present: 
[latest.log](https://github.com/SleepyTrousers/EnderIO/files/3397511/latest.log) 
[pastebin/gist/etc link here]
[latest.log](https://github.com/SleepyTrousers/EnderIO/files/3397525/latest.log)
[debug.log](https://github.com/SleepyTrousers/EnderIO/files/3397527/debug.log)

**Comment by HenryLoenwind** [comment]
We have no control over that message. Complain at https://github.com/MinecraftForge/MinecraftForge/issues if you want to get an error message that actually is useful.

**Comment by HenryLoenwind** [comment]
`[18:22:56] [Netty Client IO #3/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, creativecoredummy, ivtoolkit, littletilescore, micdoodlecore, smoothfontcore, openmodscore, foamfixcore, srm-hooks, WarpDriveCore, randompatches, securitycraft, additionalstructures, advanced-fishing, aether, animania, appleskin, appliedenergistics2, asmodeuscore, backpack, backtools, bno, battletowers, baubles, bibliocraft, bloodmoon, bookshelf, botania, buildcraftcompat, buildcraftbuilders, buildcraftcore, buildcraftenergy, buildcraftfactory, buildcraftlib, buildcraftrobotics, buildcraftsilicon, buildcrafttransport, carryon, cctweaked, computercraft, chesttransporter, chisel, chococraft, codechickenlib, cofhcore, cofhworld, extendedrenderer, coroutil, configmod, cosmeticarmorreworked, cosmeticarmorreworked|tombmanygraves, cosmiclib, craftstudioapi, ctgui, crafttweaker, crafttweakerjei, creativecore, ctm, custommainmenu, labyrinth, defaultoptions, dimdoors, ding, dungeontactics, durabilityshow, dynamiclights, dynamiclights_onfire, dynamiclights_creepers, dynamiclights_dropitems, dynamiclights_entityclasses, dynamiclights_mobequipment, dynamiclights_flamearrows, dynamiclights_floodlights, dynamiclights_otherplayers, dynamiclights_theplayer, eplus, enchdesc, endercore, enderio, enderiobase, enderioconduitsappliedenergistics, enderioconduitsopencomputers, enderioconduitsrefinedstorage, enderioconduits, enderiointegrationforestry, enderiointegrationtic, enderiointegrationticlate, enderiomachines, enderiopowertools, enderstorage, energyconverters, extrautils2, farseek, featuredservers, foamfix, forgelin, microblockcbe, forgemultipartcbe, minecraftmultipartcbe, fossil, cfm, galacticraftplanets, galacticraftcore, hardcoredarkness, helpfixer, hexxitgear, waila, hydrophobia, ic2, ic2-classic-spmod, ichunutil, industrialforegoing, infernalmobs, ironchest, jei, jrftl, rope-ladder, lightningtweaks, littletiles, mantle, mcmultipart, mobends, natura, ngtlib, recipehandler, openblocks, openmods, harvestcraft, placebo, pneumaticcraft, quacklib, quickhomes, quickteleports, railcraft, realtimeclock, dragonmounts, redstonearsenal, redstoneflux, redwoods, reforged, xreliquary, rswires, secretroomsmod, sereneseasons, simplyjetpacks, sleepingoverhaul, slideemall, smoothfont, soulshardsrespawn, stellarapi, tconstruct, teslacorelib, teslacorelib_registries, lostcities, thermaldynamics, thermalexpansion, thermalfoundation, tickratechanger, torohealthmod, traverse, bspkrscore, treecapitator, twilightforest, unidict, vanillafix, wanionlib, warpdrive, wearablebackpacks, xaerominimap, xaeroworldmap, orbis-lib, phosphor-lighting, llibrary, reauth] at SERVER`

Looks like you're trying to connect to a vanilla server with a boatload of mods installed. I'm quite sure 90+% of them do not work with vanilla servers.

**Comment by TTVInfernalKontrol** [comment]
> `[18:22:56] [Netty Client IO #3/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, creativecoredummy, ivtoolkit, littletilescore, micdoodlecore, smoothfontcore, openmodscore, foamfixcore, srm-hooks, WarpDriveCore, randompatches, securitycraft, additionalstructures, advanced-fishing, aether, animania, appleskin, appliedenergistics2, asmodeuscore, backpack, backtools, bno, battletowers, baubles, bibliocraft, bloodmoon, bookshelf, botania, buildcraftcompat, buildcraftbuilders, buildcraftcore, buildcraftenergy, buildcraftfactory, buildcraftlib, buildcraftrobotics, buildcraftsilicon, buildcrafttransport, carryon, cctweaked, computercraft, chesttransporter, chisel, chococraft, codechickenlib, cofhcore, cofhworld, extendedrenderer, coroutil, configmod, cosmeticarmorreworked, cosmeticarmorreworked|tombmanygraves, cosmiclib, craftstudioapi, ctgui, crafttweaker, crafttweakerjei, creativecore, ctm, custommainmenu, labyrinth, defaultoptions, dimdoors, ding, dungeontactics, durabilityshow, dynamiclights, dynamiclights_onfire, dynamiclights_creepers, dynamiclights_dropitems, dynamiclights_entityclasses, dynamiclights_mobequipment, dynamiclights_flamearrows, dynamiclights_floodlights, dynamiclights_otherplayers, dynamiclights_theplayer, eplus, enchdesc, endercore, enderio, enderiobase, enderioconduitsappliedenergistics, enderioconduitsopencomputers, enderioconduitsrefinedstorage, enderioconduits, enderiointegrationforestry, enderiointegrationtic, enderiointegrationticlate, enderiomachines, enderiopowertools, enderstorage, energyconverters, extrautils2, farseek, featuredservers, foamfix, forgelin, microblockcbe, forgemultipartcbe, minecraftmultipartcbe, fossil, cfm, galacticraftplanets, galacticraftcore, hardcoredarkness, helpfixer, hexxitgear, waila, hydrophobia, ic2, ic2-classic-spmod, ichunutil, industrialforegoing, infernalmobs, ironchest, jei, jrftl, rope-ladder, lightningtweaks, littletiles, mantle, mcmultipart, mobends, natura, ngtlib, recipehandler, openblocks, openmods, harvestcraft, placebo, pneumaticcraft, quacklib, quickhomes, quickteleports, railcraft, realtimeclock, dragonmounts, redstonearsenal, redstoneflux, redwoods, reforged, xreliquary, rswires, secretroomsmod, sereneseasons, simplyjetpacks, sleepingoverhaul, slideemall, smoothfont, soulshardsrespawn, stellarapi, tconstruct, teslacorelib, teslacorelib_registries, lostcities, thermaldynamics, thermalexpansion, thermalfoundation, tickratechanger, torohealthmod, traverse, bspkrscore, treecapitator, twilightforest, unidict, vanillafix, wanionlib, warpdrive, wearablebackpacks, xaerominimap, xaeroworldmap, orbis-lib, phosphor-lighting, llibrary, reauth] at SERVER`
> 
> Looks like you're trying to connect to a vanilla server with a boatload of mods installed. I'm quite sure 90+% of them do not work with vanilla servers.

Thats weird cuz the server isnt vanilla

**Comment by tyler489** [comment]
Are you trying to connect to a hub like server?

**Comment by TTVInfernalKontrol** [comment]
> Are you trying to connect to a hub like server?

well my friend cant connect to my server
no one can

**Comment by Huene** [comment]
> Are you trying to connect to a hub like server?

I have the same issue, and this is exactly what I'm trying to do, the hub server running forge with nothing on it except worldedit, the modpack is Omnifactory, and the client is throwing the same fit

**Comment by mindforger** [comment]
All servers have to have the same mod configuration, that was a thing since i asked md5 to allow for a repeated handshake which proved to be impossible until forge would add such function ... And if you know what they are dealing with youd know it did not happen. There is only one handshake and with this, the mod setup is sealed... I wohl ne happy zu be proven wrong but it is unlikely

**Comment by Huene** [comment]
> All servers have to have the same mod configuration, that was a thing since i asked md5 to allow for a repeated handshake which proved to be impossible until forge would add such function ... And if you know what they are dealing with youd know it did not happen. There is only one handshake and with this, the mod setup is sealed... I wohl ne happy zu be proven wrong but it is unlikely

That's unfortunate since it appears that only EnderIO is doing it this way, I really don't want to drop EnderIO, 

EnderIO is a fantastic mod and brings a lot to the table. Plus even if I drop it from the client so that I can connect I need to dish out special instructions for everyone to remove it from the modpack to play, which is so far from ideal it's not funny.

Any other mod, if you have the client mod, but not the server, it just ignores the client mod.  

Okay so assuming for a moment that this falls in the catagory of won't fix, does anyone know of a community server mod that simply allows the client to bypass this check, then does nothing else beyond what is required to maintain the connection? (which I imagine is nothing but I don't know the code and am not a coder anyway).  

I'm just looking for something I can throw on a vanilla forge server (1.12.2) that bypasses this check, so enderio clients can connect to the otherwise vanilla server, to be handed off to an enderio enabled server after connecting.

**Comment by mindforger** [comment]
you could pick up the ball and call out md5 and lex manos to dig this up and start working on it again, but i won't touch that topic again even with a pair of pincer

having the ability to redo the handshake (and "reboot" the mods on the fly client side when changing dimension) would be awesome to have a multi modded server but this is in the ballpark of forge to implement and the mod writers, as theya need to support this reboot feature in some way

but i got an idea for you, that might hit the spot, i am not yet up to date on how the mods are going but there was this staging mod, where you could setup what mods a player is able to use and see blockwise, it behaved like a killswitch until you reach a certain stage

you can probably use this mod to control the available content per server instance and still have all server running the same modpack!

Also please correct me if i am wrong on this one but my last information on this kind of setup i have from testing is
1) you can connect to the unmodded lobby and then switch over to a modded server instance with mods that don't try to sync stuff right at the beginning because the handshake is delayed until you virtually switch dimensions (i got this working with a special build from md5)
2) you can switch back from that instance to the lobby, as long as no mod changes standard blocks or you will at least glitch out
3) you can never ever switch to any other mod configuration when done the handshake, with any modded server, already once

**Comment by connorch** [comment]
I'm trying to set up a Tekxit server and I'm running into this same error, even when the mods are copied over exactly as they are on the client side.  Is there anything I can do on my side to fix this?

**Comment by TTVInfernalKontrol** [comment]
im sorry but i dont know how to fix


________________________________
De: Connor Chevli <notifications@github.com>
Enviado: 2 de agosto de 2019 01:29
Para: SleepyTrousers/EnderIO <EnderIO@noreply.github.com>
Cc: TTVInfernalKontrol <xavisilva2011@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [SleepyTrousers/EnderIO] [1.12.2]Rejecting connection SERVER: Ender IO: Failed mod's custom NetworkCheckHandler (#5177)


I'm trying to set up a Tekxit server and I'm running into this same error, even when the mods are copied over exactly as they are on the client side. Is there anything I can do on my side to fix this?
