### ISSUE TITLE
Simple Wired Charger compatibility

### ISSUE THREAD

**Issue by Snownee** [SleepyTrousers/EnderIO#5306]
#### Issue Description:

Hello, I wrote a simple Forge energy handler ([here](https://github.com/Snownee/LightingWand/blob/master/src/main/java/snownee/lightingwand/common/EnergyRepair.java)) that allows item get repaired if being charged. As the `getMaxEnergyStored()` always returns 0, and [this line of codes](https://github.com/SleepyTrousers/EnderIO/blob/master/enderio-machines/src/main/java/crazypants/enderio/machines/machine/wired/TileWiredCharger.java#L167), the item can never be charged. So I am wondering what we can do to let things work?

____
#### Affected Versions):
- EnderIO: 5.1.52
- Minecraft: 1.12.2

**Comment by Ommina** [comment]
This appears to be an issue with your item.  You're telling the charger that the item can't store any energy; so what's the charger to do?

**Comment by Snownee** [comment]
@Ommina I think it does not have energy stored does not mean it can not receive energy. Received energy will be directly converted to durability, so returning 0 makes sense

**Comment by Snownee** [comment]
misclick

**Comment by Ommina** [comment]
I dunno.  I get your point, but it seems to me this is how any sane item charger (wireless or otherwise) would behave.

"Hi!" says the charger.  "How much energy can you store?"
"None at all!" says the item.
"Ah."

Now, you argue that your item is not actually interested in buffering any energy; you just want to consume what is offered as it arrives.  And I get your logic, but I really feel you'll be swimming upstream here.  Even if the fine people in EnderIO-land buy the argument, I expect you'll just run into the same issue with other mod's chargers.

**Comment by HenryLoenwind** [comment]
It runs into the "max stored" check here, but that's not all. If we didn't use that to determine charging speed, it would fail at the "are you full already" check and would be ejected instantly. Or crash the game if some machine wants to show `(0 / 0 * 100) + "%"` charging state.

My recommendation is to calculate all those values from the durability and max durability of the item.

**Comment by Snownee** [comment]
Thanks for your advice
