### ISSUE TITLE
Server Crashes. ENDER IO: Found the following problem(s) with your installation....

### ISSUE THREAD

**Issue by dtoxftw** [SleepyTrousers/EnderIO#5307]
Skyfactory 3

Full crash log: [https://paste.feed-the-beast.com/view/e24488c2](https://paste.feed-the-beast.com/view/e24488c2)

e24488c2

We're having constant server crashes that FTB originally believed to be a Refined Storage controller issue.  After addressing that, things seem a little more stable but crashing continues and world files keep corrupting, forcing us to revert to several versions back.   I imagine there are a few issues but wanted to address these Ender IO logs. 

*** The RF API that is being used (1.5.0 from (guessing) null) differes from that that is reported as being loaded (1.8.9R1.2.0B1 from SonarCore-1.10.2-3.3.0.jar).
                    It is a supported version, but that difference may lead to problems.
                  * Our API got loaded from MoarSigns-1.10.2-4.2.3.9.jar. That's unexpected.**

I didn't want to start messing with versions until I confirmed that should be addressed. And the moarsigns thing is strange.  Any help is appreciated, thanks!

[https://paste.feed-the-beast.com/view/e24488c2]

Edit: fixed link

**Comment by VT-14** [comment]
Your Server Watchdog is closing the server because it's 'hanging' (freezing for more than a set amount of time).

I see Locks and Refined Storage both appearing in the various stack traces, but I don't know how trustworthy a Watchdog report is.  I would suggest tweaking the settings for whatever watchdog you are using, and using a Profiler like Sampler if you want to figure out what is causing your performance issues.

****

Ender IO does not appear to have anything to do with this crash.  In fact, the line immediately proceeding the one you posted says:

`EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):`

**Comment by dtoxftw** [comment]
Yes I'm well aware of what the rude ass message says.  Which is why i was reluctant to even post here.  I do appreciate the help though, (genuinely) its just that this is greek to most people.  I don't know what stacktrace means, hell I don't even know what a watchdog is.  My main concern was the version # issue and I didn't want to start messing with that before getting some sort of confirmation.

**Comment by tterrag1098** [comment]
The message is there for a reason. This is it, actually.

Always report bugs to the modpack author *first*. They can handle triaging to the correct mod author.

**Comment by dtoxftw** [comment]
I did contact them. As. I. said. 

You didn't address the version # or the moarsigns error. All I got was "herp derp can't trust the watchdog."  How fucking lazy.

**Comment by tterrag1098** [comment]
@VT-14 told you exactly what the problem was. You asked for help and got an answer, it's not EnderIO's fault. We didn't address the other points because they aren't the problem.
