### ISSUE TITLE
[Suggestion] Way to recycle obsolete beginner machines

### ISSUE THREAD

**Issue by Venom31** [SleepyTrousers/EnderIO#5387]
#### Issue Description:

Not a bug, but a suggestion. I noticed that the new and improved progression makes the beginner tier "Simple" machines pretty much mandatory. Which is fine, but the way they are upgraded to regular tier requires more resources than making regular tier from scratch. Therefore, all players usually go that route, ditching simple machines afterwards. Maybe a recipe for recycling them could be added, e.g. in SAG Mill, such that you get some resources back.

#### What happens:

Due to mismatch in recipe costs, one crafts regular (tier 2?) machines from scratch, disregarding the upgrade possibility.

#### What I would like to happen:

Either better match recipe costs, or e.g. make SAG Mill grind simple machines into constituent Simple Machine Chassis plus maybe the most important ingredients (iron, redstone) used to craft that machine.

That'd be very nice... unless it's 100% intended design, in which case sorry for taking your time.

**Comment by tyler489** [comment]
What machine takes more resources for the upgrade recipe than to craft it from scratch

**Comment by VT-14** [comment]
From my understanding, the recipes are set up so upgrading a machine (Simple -> normal) is cheaper than a direct crafting recipe (nothing -> normal), but going from nothing through Simple is more expensive (nothing -> Simple -> normal).

With only Ender IO (no other mods adding similar recipes) you need some of the Simple Machines to get the materials necessary to upgrade to later ones.  Upgrading that machine should be cheaper than just crafting a new one:

Simple SAG Mill -> normal SAG Mill

2 Dark Steel Ingots, 1 Chassis, 2 Dark Steel Gears.  Plus the Simple SAG Mill *you already have* so that's effectively free.

Nothing -> normal SAG Mill

2 Dark Steel Ingots, 1 Chassis, 2 Dark Steel Gears, so the same as above... Plus 3 Flint and 1 Piston.

****

The only questionable one that comes to my mind is the Alloy Smelter recipe, which combines a Simple Alloy Smelter (only does Alloys, no Furnace recipes), and the Simple Powered Furnace (only does furnace recipes).  A lot of people may choose to forego the Simple Powered Furnace, in which case crafting one just for the upgrade recipe would cost more than just crafting an Alloy Smelter directly, but that's one machine combining two 'simple' variants.

**Comment by Venom31** [comment]
To upgrade, one uses Industrial Machine Chassis (which is a Simple Machine Chassis plus some extra) on top of already used Simple Machine Chassis. So the answer is, pretty much every regular tier machine takes more resources for the upgrade than to craft it from scratch. Photovoltaic Cells take other resource, but whatever, you get the point.

I added Excel spreadsheet to illustrate it for SAG Mill, Alloy Smelter and Stirling Generator.
[EnderIO simple machines resources.xlsx](https://github.com/SleepyTrousers/EnderIO/files/4690826/EnderIO.simple.machines.resources.xlsx)
Mismatches are highlighted yellow and orange, orange being the more expensive ones.

**Comment by Venom31** [comment]
Oh, I see what you're saying now, @tyler489, after reading your question more thoroughly. I wasn't referring to extra resources per upgrade vs making a T2 machine from scratch, but only total costs of tier 1 + upgrade vs tier 2 from scratch (but you have to have T1 made first!). In @VT-14's reply, the Alloy Smelter is definitely the most prominent example of where its upgrade recipe is almost useless, but that wasn't my point.

I suggested making the alternate route with making T1, then T2 without upgrading viable by allowing to get some items back from now useless leaky T1 machines to go forward.

**Comment by tyler489** [comment]
the whole point of the upgrade recipe is that you are forced to make the tier 1 machines first upgrade them to tier 2 and then you can make tier 2 directly. sure it requires another chassis but so does making a new machine.

**Comment by Venom31** [comment]
Now that I've tallied up the alternate route, I see it's usually more expensive to make T2 from scratch after making T1, only exception being with skipping Simple Powered Furnace for Alloy Smelter. Guess I'll just void Simple Alloy Smelter after crafting its T2 then.
