### ISSUE TITLE
The item cables do not connect with the mod. Refined Storage.

### ISSUE THREAD

**Issue by Abril253** [SleepyTrousers/EnderIO#5421]
#### Issue Description:
The item cables do not connect with the mod. Refined Storage.

#### What happens:
The item cables do not connect with the mod. Refined Storage
[https://i.imgur.com/8zOIksI.png](url)

#### What you expected to happen:
Such a connection
[https://i.imgur.com/eMd9xoi.png](url)

#### Steps to reproduce:

1.Assemble the Refined Storage system
2.With the ender-io pipes try to extract items by connecting them to the storage panel
3.ERROR. There is no connection between both systems
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.2.59
- EnderCore: EnderCore-1.12.2-0.5.76
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2854
- SpongeForge? No
- Optifine? Yes. OptiFine_1.12.2_HD_U_F5
- Single Player and/or Server? Single player

#### Your most recent log file where the issue was present: 

[2020-08-16-4.log](https://github.com/SleepyTrousers/EnderIO/files/5080934/2020-08-16-4.log)

**Comment by VT-14** [comment]
RS Grids do not have any inventories for Item Conduits to connect to.  Grids are for player interactions, not for automation.

RS Conduits connect to grids because they are extending the RS Network.  They are like RS's own cables.

If you want to move items into or out of RS using external piping (like Ender IO's Item Conduits) then you need to use an RS Interface.  You can also move the Storage Disks (not the items contained on said Disks) in/out of things like the Disk Drive and Disk Manipulator since those are also actual inventories.

**Comment by Abril253** [comment]
> RS Grids no tiene inventarios a los que conectar los conductos de artículos. Las cuadrículas son para interacciones de jugadores, no para automatización.
> 
> Los conductos RS se conectan a las redes porque están ampliando la red RS. Son como los propios cables de RS.
> 
> Si desea mover elementos dentro o fuera de RS utilizando tuberías externas (como los conductos de elementos de Ender IO), debe usar una interfaz RS. También puede mover los discos de almacenamiento (no los elementos contenidos en dichos discos) dentro o fuera de cosas como la unidad de disco y el manipulador de disco, ya que también son inventarios reales.

But before if I did
