### ISSUE TITLE
The Ender with upgrade "Direct" cannot pick up extra Ender IO sword drops

### ISSUE THREAD

**Issue by ButterCatz** [SleepyTrousers/EnderIO#5444]
#### Issue Description:

Dark steel upgrade "Direct" cannot pick up loots from enderman.

#### What happens:

The Ender upgrade "Direct" cannot pick up loots (pearls and heads) from enderman.
I also tested on other animals/mobs/blocks, it seems that only enderman was affected.

#### What you expected to happen:

Pick up those pearls & heads

#### Steps to reproduce:

1.Get yourself a "The Ender" or "The Ender MK2" with upgrade "Direct"
2.Kill an enderman
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.2.61.jar
- EnderCore: 1.12.2-0.5.76.jar
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- No SpongeForge
- No Optifine 
- Single Player

**Comment by HenryLoenwind** [comment]
Another one of those cases where Forge should have an "add stuff" and "remove stuff" event... grrr

I moved up the code that adds our Enderman head to an earlier priority, but please note that we cannot capture vanilla head drops---those are spawned directly in the world instead of being dropped from the mob.
