### ISSUE TITLE
Enchanter and other XP using machines should be able to pull XP from an XP obelisk

### ISSUE THREAD

**Issue by Tomodachi94** [SleepyTrousers/EnderIO#5461]
A few minutes ago, I was looking for a way to automate the Enchanter.
I found no way to supply the experience needed for the operation.
**MY PROPOSAL:** Enchanters should be able to draw experience levels from XP obelisks.

**Comment by tyler489** [comment]
enchanters don't have "exp tank" which would mean a rewrite of the enchanted.

**Comment by Tomodachi94** [comment]
oh... frack.

**Comment by Tomodachi94** [comment]
oh... crud.

**Comment by Tomodachi94** [comment]
couldn't it use the obelisk itself as a tank, if one is present in say 10 blocks?

**Comment by VT-14** [comment]
Making the Enchanter consume Liquid XP rather than levels from the player directly would require a major rewrite of the enchanter's system.

I'm not a coder, but IIRC from previous conversations about possibly doing that, making the Enchanter use Liquid XP would basically require turning it into a machine (rather than mirroring the vanilla anvil).  One of the consequences of doing that would be loosing the preview ability.  There could also be recipe/automation issues, such as starting to insert the items for a Protection IV book from Conduits, but it crafts a Protection I book before it gets all of the items, plus now the Enchanter is jammed with extra items.

It is not a trivial tweak.

**Comment by Tomodachi94** [comment]
Oh. Not ideal then?
I can live without it.
