### ISSUE TITLE
Farming Station crash with AgriCraft Poppy Seed (1.12.2)

### ISSUE THREAD

**Issue by DeadSix27** [SleepyTrousers/EnderIO#5532]
#### Issue Description:

Farming station crashed with Agricraft poppy seeds at full age.

(Looked a bit through the issue tracker, couldn't find a similar issue, at least not after a light search)

#### What happens:

Crash

#### What you expected to happen:

No crash

#### Steps to reproduce:

1. Plant agricraft poppy seed (10/10/10)
2. Start farming station at range lvl 4
3. Crash

Crash log (tells versions):

https://gist.github.com/DeadSix27/8023d16cd498dd79bf02c75ac7e6e0f7

**Comment by LumberWizard** [comment]
Can repro with just Ender IO 5.3.70 (and EnderCore 0.5.76), Agricraft 2.12.0-b2 (and InifnityLib 1.12.1), and JEI.

**Comment by embeddedt** [comment]
This is most likely occuring because AgriCraft is [compiling against an old version](https://github.com/AgriCraft/AgriCraft/blob/def0e8b8562edd3e07955910773f1e96e20de09d/build.gradle#L106) of EnderIO's API. Specifically, their [Farmer Joe implementation](https://github.com/AgriCraft/AgriCraft/blob/def0e8b8562edd3e07955910773f1e96e20de09d/src/main/java/com/infinityraider/agricraft/compat/enderio/AgriFarmerJoe.java#L43) creates a list of EntityItems, while EnderIO now expects a list of `Pair<BlockPos, ItemStack>`.

The change in EnderIO was introduced in [this commit](https://github.com/SleepyTrousers/EnderIO/commit/e62f4cb61553a62a6af4b048151be3ccff171766#diff-24b08f62876ac4ed1cf2eb73d81b1b58cda307ab0b5d3d0d33a57816b0ffc3d0).

**Comment by DeadSix27** [comment]
Thanks for your work @embeddedt ! Very appreciated <3 hopefully they'll merge your PR and thanks to you all for your time.

**Comment by embeddedt** [comment]
The PR was merged, however, I am unsure if/when there will be another AgriCraft release, so here is a compiled JAR from https://github.com/AgriCraft/AgriCraft/commit/79f226d7a5f1b005107bc548f78c9a849217f8fa:

[agricraft.zip](https://github.com/SleepyTrousers/EnderIO/files/7086644/agricraft.zip)

**Comment by davidlee0512** [comment]
I used the new jar but Farming Station would harvest a non-mature crop and the crop disappear(would not return the seed). I use diamahlia seed for testing. This also happens on cross crop(double Crop Stick)
