### ISSUE TITLE
[RFE]: Conduit settings copy & paste

### ISSUE THREAD

**Issue by MatthiasMann** [SleepyTrousers/EnderIO#590]
A copy & paste card to transfer interface settings from one conduit to another would be nice

**Comment by krakentoa** [comment]
I tried using this to copy the active sides (sides with  mode field set to "In/Out" field) of an insulated redstone conduit. It didn't work, it only copied other fields, and only if the corresponding sides were already set to "In/Out".
 I'm using 2.2.6.3, but I checked the changelog and there's been no changes to the conduit probe since then. Later I'll try with the newest one.
